//
//  TabooWordsViewModel.swift
//  TabooWordGame
//
//  Created by Batu on 23.04.2024.
//
import Foundation

class TabooWordsViewModel {
    
    var score: Int = 0
    var passAttempts = 3
    
    private let tabooWords: [TabooWord] = [
            TabooWord(goalWord: "Köpek", tabooWords: ["Kedi", "Hav", "Kuyruk", "Oyuncak", "Mama"]),
            TabooWord(goalWord: "Elma", tabooWords: ["Meyve", "Kırmızı", "Yeşil", "Ağaç", "Tatlı"]),
            TabooWord(goalWord: "Deniz", tabooWords: ["Su", "Kum", "Dalga", "Plaj", "Yüzmek"]),
            TabooWord(goalWord: "Kitap", tabooWords: ["Sayfa", "Okumak", "Yazar", "Roman", "Kütüphane"]),
            TabooWord(goalWord: "Kuş", tabooWords: ["Kanat", "Uçmak", "Gaga", "Yuva", "Ötmek"]),
            TabooWord(goalWord: "Çiçek", tabooWords: ["Renk", "Koku", "Yaprak", "Bahçe", "Papatya"]),
            TabooWord(goalWord: "Masa", tabooWords: ["Sandalye", "Yemek", "Mobilya", "Oturmak", "Ahşap"]),
            TabooWord(goalWord: "Telefon", tabooWords: ["Aramak", "Mesaj", "Konuşmak", "Akıllı", "Ekran"]),
            TabooWord(goalWord: "Saat", tabooWords: ["Zaman", "Dakika", "Kronometre", "Kol", "Alarm"]),
            TabooWord(goalWord: "Müzik", tabooWords: ["Şarkı", "Nota", "Enstrüman", "Melodi", "Dinlemek"]),
            TabooWord(goalWord: "Film", tabooWords: ["Sinema", "Oyuncu", "Yönetmen", "Sahne", "Ekran"]),
            TabooWord(goalWord: "Uçak", tabooWords: ["Pilot", "Havalimanı", "Kanat", "Uçuş", "Yolcu"]),
            TabooWord(goalWord: "Ayakkabı", tabooWords: ["Ayak", "Koşmak", "Giyinmek", "Topuk", "Deri"]),
            TabooWord(goalWord: "Bisiklet", tabooWords: ["Pedal", "Tekerlek", "Zil", "Yol", "Kask"]),
            TabooWord(goalWord: "Kahve", tabooWords: ["Bardak", "Kafein", "İçmek", "Sabah", "Tat"]),
            TabooWord(goalWord: "Televizyon", tabooWords: ["Kanal", "Dizi", "Film", "Ekran", "Uzaktan Kumanda"]),
            TabooWord(goalWord: "Çikolata", tabooWords: ["Tatlı", "Kakao", "Yemek", "Şeker", "Bar"]),
            TabooWord(goalWord: "Domates", tabooWords: ["Kırmızı", "Sebze", "Salata", "Sos", "Bahçe"]),
            TabooWord(goalWord: "Köprü", tabooWords: ["Nehir", "Yol", "Trafik", "Geçmek", "Bağlamak"]),
            TabooWord(goalWord: "Oda", tabooWords: ["Duvar", "Kapı", "Mobilya", "Pencere", "Mekan"]),
            TabooWord(goalWord: "Sinema", tabooWords: ["Film", "Ekran", "Oyuncu", "Koltuk", "Yönetmen"]),
            TabooWord(goalWord: "Bisiklet", tabooWords: ["Tekerlek", "Pedal", "Yol", "Kask", "Zil"]),
            TabooWord(goalWord: "Kedi", tabooWords: ["Tüy", "Miyav", "Pat", "Kum", "Mama"]),
            TabooWord(goalWord: "Gözlük", tabooWords: ["Cam", "Görmek", "Burun", "Yüz", "Çerçeve"]),
            TabooWord(goalWord: "Rüzgar", tabooWords: ["Esinti", "Soğuk", "Hava", "Kuvvetli", "Dalga"]),
            TabooWord(goalWord: "Patates", tabooWords: ["Kızartma", "Sebze", "Yemek", "Cips", "Sarı"]),
            TabooWord(goalWord: "Kapı", tabooWords: ["Açmak", "Kapatmak", "Anahtar", "Giriş", "Kol"]),
            TabooWord(goalWord: "Sandalye", tabooWords: ["Oturmak", "Masa", "Ahşap", "Mobilya", "Ayak"]),
            TabooWord(goalWord: "Çay", tabooWords: ["İçmek", "Bardak", "Kupa", "Demlemek", "Sıcak"]),
            TabooWord(goalWord: "Çanta", tabooWords: ["Okul", "Eşya", "Sırt", "Taşımak", "Deri"]),
            TabooWord(goalWord: "Pasta", tabooWords: ["Doğum Günü", "Yemek", "Tatlı", "Krema", "Dilim"]),
            TabooWord(goalWord: "Balık", tabooWords: ["Deniz", "Su", "Yüzmek", "Yemek", "Yunus"]),
            TabooWord(goalWord: "Karpuz", tabooWords: ["Meyve", "Yaz", "Tatlı", "Kırmızı", "Çekirdek"]),
            TabooWord(goalWord: "Aslan", tabooWords: ["Hayvan", "Orman", "Yele", "Kükreme", "Kedi"]),
            TabooWord(goalWord: "Tavuk", tabooWords: ["Yumurta", "Civciv", "Et", "Kanat", "Horoz"]),
            TabooWord(goalWord: "Gitar", tabooWords: ["Müzik", "Çalmak", "Tel", "Enstrüman", "Nota"]),
            TabooWord(goalWord: "Güneş", tabooWords: ["Işık", "Sıcak", "Gökyüzü", "Gündüz", "Yıldız"]),
            TabooWord(goalWord: "Kumanda", tabooWords: ["Televizyon", "Kontrol", "Tuş", "Pil", "Kanal"]),
            TabooWord(goalWord: "Mektup", tabooWords: ["Zarf", "Posta", "Yazmak", "Göndermek", "Adres"]),
            TabooWord(goalWord: "Şapka", tabooWords: ["Kafa", "Giyinmek", "Yaz", "Gölge", "Moda"]),
            TabooWord(goalWord: "Kalem", tabooWords: ["Yazmak", "Kurşun", "Kağıt", "Silgi", "Renk"]),
            TabooWord(goalWord: "Çanta", tabooWords: ["Okul", "Eşya", "Sırt", "Taşımak", "Deri"]),
            TabooWord(goalWord: "Anahtar", tabooWords: ["Kapı", "Açmak", "Kilitlemek", "Metal", "Daire"]),
            TabooWord(goalWord: "Bebek", tabooWords: ["Ağlamak", "Kundak", "Çocuk", "Uyumak", "Süt"]),
            TabooWord(goalWord: "Oyun", tabooWords: ["Eğlence", "Kazanmak", "Kaybetmek", "Kurallar", "Takım"]),
            TabooWord(goalWord: "Kum", tabooWords: ["Plaj", "Sarı", "Çöl", "Deniz", "Kumdan Kale"]),
            TabooWord(goalWord: "Para", tabooWords: ["Banknot", "Madeni", "Cüzdan", "Zengin", "Harcama"]),
            TabooWord(goalWord: "Şemsiye", tabooWords: ["Yağmur", "Açmak", "Kapamak", "Gölge", "Rüzgar"]),
            TabooWord(goalWord: "Havlu", tabooWords: ["Banyo", "Kurulamak", "Yumuşak", "Bez", "Pamuk"]),
            TabooWord(goalWord: "Takım Elbise", tabooWords: ["Ceket", "Pantolon", "Gömlek", "Kravatsız", "Kumaş"]),
            TabooWord(goalWord: "Orman", tabooWords: ["Ağaç", "Yeşil", "Doğa", "Yürüyüş", "Hayvan"]),
            TabooWord(goalWord: "Karpuz", tabooWords: ["Meyve", "Kırmızı", "Yaz", "Tatlı", "Çekirdek"]),
            TabooWord(goalWord: "Bebek", tabooWords: ["Ağlamak", "Kundak", "Çocuk", "Uyumak", "Süt"]),
            TabooWord(goalWord: "Gözlük", tabooWords: ["Cam", "Görmek", "Burun", "Yüz", "Çerçeve"]),
            TabooWord(goalWord: "Martı", tabooWords: ["Deniz", "Kuş", "Uçmak", "Beyaz", "Gaga"]),
            TabooWord(goalWord: "Bardak", tabooWords: ["İçmek", "Su", "Çay", "Kupa", "Cam"]),
            TabooWord(goalWord: "Meyve", tabooWords: ["Elma", "Armut", "Tatlı", "Ağaç", "Yemek"]),
            TabooWord(goalWord: "Kelebek", tabooWords: ["Kanat", "Uçmak", "Renk", "Çiçek", "Tırtıl"]),
            TabooWord(goalWord: "Göz", tabooWords: ["Görmek", "Renk", "Işık", "Kirpik", "Lens"]),
            TabooWord(goalWord: "Deniz", tabooWords: ["Mavi", "Su", "Yüzmek", "Kum", "Tekne"]),
            TabooWord(goalWord: "Kapı", tabooWords: ["Ev", "Açmak", "Kapatmak", "Anahtar", "Zil"]),
            TabooWord(goalWord: "Rüzgar", tabooWords: ["Esinti", "Soğuk", "Hava", "Kuvvetli", "Dalga"]),
            TabooWord(goalWord: "Elbise", tabooWords: ["Kıyafet", "Giyinmek", "Kadın", "Moda", "Renk"]),
            TabooWord(goalWord: "Çiçek", tabooWords: ["Bahçe", "Renk", "Koku", "Tohum", "Güzel"]),
            TabooWord(goalWord: "Futbol", tabooWords: ["Top", "Saha", "Gol", "Kale", "Maç"]),
            TabooWord(goalWord: "Hastane", tabooWords: ["Doktor", "Hemşire", "Hasta", "Muayene", "Ameliyat"]),
            TabooWord(goalWord: "Tiyatro", tabooWords: ["Oyun", "Sahne", "Aktör", "Seyirci", "Perde"]),
            TabooWord(goalWord: "Kamera", tabooWords: ["Fotoğraf", "Video", "Çekim", "Lens", "Tripod"]),
            TabooWord(goalWord: "Buzdolabı", tabooWords: ["Soğutmak", "Yiyecek", "Buz", "Kapı", "Elektrik"]),
            TabooWord(goalWord: "Çaydanlık", tabooWords: ["Çay", "Su", "Kaynamak", "Demlik", "Kapağı"]),
            TabooWord(goalWord: "Sabun", tabooWords: ["Temizlik", "Köpük", "El", "Duş", "Kokulu"]),
            TabooWord(goalWord: "Sokak", tabooWords: ["Yol", "Ev", "Araç", "Yaya", "Gece"]),
            TabooWord(goalWord: "Tepe", tabooWords: ["Yüksek", "Dağ", "Tırmanmak", "Manzara", "Yeşil"]),
            TabooWord(goalWord: "Vazo", tabooWords: ["Çiçek", "Seramik", "Dekorasyon", "Su", "Masa"]),
            TabooWord(goalWord: "Yelkenli", tabooWords: ["Deniz", "Rüzgar", "Yelken", "Tekne", "Yarış"]),
            TabooWord(goalWord: "Yemek", tabooWords: ["Pişirmek", "Tat", "Yemek", "Restoran", "Mutfak"]),
            TabooWord(goalWord: "Yolcu", tabooWords: ["Seyahat", "Uçak", "Otobüs", "Tren", "Bagaj"]),
            TabooWord(goalWord: "Zürafa", tabooWords: ["Hayvan", "Uzun Boyun", "Afrika", "Yemek", "Sarışın"]),
            TabooWord(goalWord: "Zeytin", tabooWords: ["Yeşil", "Siyah", "Ağaç", "Ege", "Yağ"]),
            TabooWord(goalWord: "Yunus", tabooWords: ["Deniz", "Balık", "Mavi", "Şov", "Akvaryum"]),
            TabooWord(goalWord: "Kahve", tabooWords: ["Bardak", "Kafein", "İçmek", "Sabah", "Tat"]),
            TabooWord(goalWord: "Tavşan", tabooWords: ["Kulak", "Havuç", "Sıçramak", "Post", "Koşmak"]),
            TabooWord(goalWord: "Çanta", tabooWords: ["Okul", "Eşya", "Sırt", "Taşımak", "Deri"]),
            TabooWord(goalWord: "Saat", tabooWords: ["Zaman", "Dakika", "Kronometre", "Kol", "Alarm"]),
            TabooWord(goalWord: "Zaman", tabooWords: ["Saat", "An", "Dakika", "Geçmek", "Hız"]),
            TabooWord(goalWord: "Dakika", tabooWords: ["Saat", "Zaman", "Saniye", "Ölçmek", "Saat"]),
            TabooWord(goalWord: "Kronometre", tabooWords: ["Saat", "Zaman", "Ölçmek", "Yarış", "Spor"]),
            TabooWord(goalWord: "Kol", tabooWords: ["Saat", "Vücut", "El", "Bilek", "Omuz"]),
            TabooWord(goalWord: "Alarm", tabooWords: ["Saat", "Zil", "Uyandırmak", "Gün", "İş"]),
            TabooWord(goalWord: "Pilot", tabooWords: ["Uçak", "Gökyüzü", "Kokpit", "Uçuş", "Hava"]),
            TabooWord(goalWord: "Havalimanı", tabooWords: ["Uçak", "Yolcu", "Terminal", "Uçuş", "Bagaj"]),
            TabooWord(goalWord: "Kanat", tabooWords: ["Uçak", "Kuş", "Uçuş", "Yolcu", "Motor"]),
            TabooWord(goalWord: "Uçuş", tabooWords: ["Uçak", "Hava", "Yolcu", "Seyahat", "Pilot"]),
            TabooWord(goalWord: "Yolcu", tabooWords: ["Uçak", "Tren", "Otobüs", "Seyahat", "Bilet"]),
            TabooWord(goalWord: "Ayak", tabooWords: ["Ayakkabı", "Parmak", "Yürümek", "Spor", "Koku"]),
            TabooWord(goalWord: "Koşmak", tabooWords: ["Spor", "Hızlı", "Yarış", "Egzersiz", "Park"]),
            TabooWord(goalWord: "Giyinmek", tabooWords: ["Kıyafet", "Elbise", "Değişmek", "Moda", "Gardırop"]),
            TabooWord(goalWord: "Topuk", tabooWords: ["Ayakkabı", "Ayak", "Yüksek", "Kadın", "Çizme"]),
            TabooWord(goalWord: "Deri", tabooWords: ["Ayakkabı", "Hayvan", "Cilt", "Giysi", "Mobilya"]),
            TabooWord(goalWord: "Bisiklet", tabooWords: ["Pedal", "Tekerlek", "Zil", "Yol", "Kask"]),
            TabooWord(goalWord: "Pedal", tabooWords: ["Bisiklet", "Ayak", "Hız", "Tekerlek", "Yol"]),
            TabooWord(goalWord: "Tekerlek", tabooWords: ["Bisiklet", "Araba", "Yol", "Pedal", "Lastik"]),
            TabooWord(goalWord: "Zil", tabooWords: ["Bisiklet", "Çan", "Ses", "Alarm", "Çalmak"]),
            TabooWord(goalWord: "Yol", tabooWords: ["Bisiklet", "Trafik", "Yürümek", "Araba", "Seyahat"]),
            TabooWord(goalWord: "Kitap", tabooWords: ["Sayfa", "Okumak", "Yazar", "Roman", "Kütüphane"]),
            TabooWord(goalWord: "Sayfa", tabooWords: ["Kitap", "Kağıt", "Yazı", "Okumak", "Kalem"]),
            TabooWord(goalWord: "Okumak", tabooWords: ["Kitap", "Göz", "Kelime", "Yazı", "Eğitim"]),
            TabooWord(goalWord: "Yazar", tabooWords: ["Kitap", "Roman", "Yazmak", "Edebiyat", "İsim"]),
            TabooWord(goalWord: "Roman", tabooWords: ["Kitap", "Hikaye", "Yazar", "Edebiyat", "Sayfa"]),
            TabooWord(goalWord: "Kütüphane", tabooWords: ["Kitap", "Okumak", "Sessiz", "Raf", "Bilgi"]),
            TabooWord(goalWord: "Kanat", tabooWords: ["Kuş", "Uçmak", "Tüy", "Hava", "Güvercin"]),
            TabooWord(goalWord: "Uçmak", tabooWords: ["Kuş", "Kanat", "Hava", "Yükseklik", "Pilot"]),
            TabooWord(goalWord: "Gaga", tabooWords: ["Kuş", "Yemek", "Sert", "Uçmak", "Ötmek"]),
            TabooWord(goalWord: "Yuva", tabooWords: ["Kuş", "Ev", "İnşa", "Yumurta", "Aile"]),
            TabooWord(goalWord: "Ötmek", tabooWords: ["Kuş", "Ses", "Sabah", "Şarkı", "Kanarya"]),
            TabooWord(goalWord: "Tatlı", tabooWords: ["Şeker", "Yemek", "Pasta", "Tat", "Meyve"]),
            TabooWord(goalWord: "Kakao", tabooWords: ["Çikolata", "Tropik", "Fasulye", "Bitter", "Toz"]),
            TabooWord(goalWord: "Yemek", tabooWords: ["Tat", "Lezzet", "Mutfak", "Besin", "Öğün"]),
            TabooWord(goalWord: "Şeker", tabooWords: ["Tatlı", "Yemek", "Tat", "Tatlandırıcı", "Şurup"]),
            TabooWord(goalWord: "Bar", tabooWords: ["Çikolata", "Şeker", "Atıştırmalık", "Enerji", "Kalori"]),
            TabooWord(goalWord: "Deniz", tabooWords: ["Su", "Kum", "Dalga", "Plaj", "Yüzmek"]),
            TabooWord(goalWord: "Su", tabooWords: ["İçmek", "H2O", "Deniz", "Yağmur", "Hayat"]),
            TabooWord(goalWord: "Kum", tabooWords: ["Plaj", "Çöl", "Deniz", "Sarı", "İnce"]),
            TabooWord(goalWord: "Dalga", tabooWords: ["Deniz", "Su", "Hareket", "Rüzgar", "Sörf"]),
            TabooWord(goalWord: "Plaj", tabooWords: ["Deniz", "Kum", "Güneş", "Tatil", "Mayo"]),
            TabooWord(goalWord: "Yüzmek", tabooWords: ["Su", "Havuz", "Deniz", "Serinlemek", "Spor"]),
            TabooWord(goalWord: "Kanal", tabooWords: ["Televizyon", "Program", "Yayın", "Haber", "Frekans"]),
            TabooWord(goalWord: "Dizi", tabooWords: ["Televizyon", "Bölüm", "Drama", "Oyuncu", "Senaryo"]),
            TabooWord(goalWord: "Film", tabooWords: ["Sinema", "Oyuncu", "Yönetmen", "Sahne", "Ekran"]),
            TabooWord(goalWord: "Uzaktan Kumanda", tabooWords: ["Televizyon", "Buton", "Kontrol", "Pil", "Cihaz"]),
            TabooWord(goalWord: "Tüy", tabooWords: ["Kedi", "Kuş", "Yumuşak", "Kürk", "Kanat"]),
            TabooWord(goalWord: "Miyav", tabooWords: ["Kedi", "Ses", "Hayvan", "Çağırmak", "Pat"]),
            TabooWord(goalWord: "Pat", tabooWords: ["Kedi", "Pati", "Tırnak", "Dokunmak", "Oynamak"]),
            TabooWord(goalWord: "Kum", tabooWords: ["Kedi", "Tuvalet", "Deniz", "Çöl", "Oyun"]),
            TabooWord(goalWord: "Mama", tabooWords: ["Yemek", "Kedi", "Köpek", "Beslemek", "Hayvan"]),
            TabooWord(goalWord: "Meyve", tabooWords: ["Elma", "Sebze", "Tatlı", "Yiyecek", "Ağaç"]),
            TabooWord(goalWord: "Kırmızı", tabooWords: ["Renk", "Elma", "Kan", "Yangın", "Çilek"]),
            TabooWord(goalWord: "Yeşil", tabooWords: ["Renk", "Elma", "Yaprak", "Ağaç", "Doğa"]),
            TabooWord(goalWord: "Ağaç", tabooWords: ["Orman", "Yaprak", "Meyve", "Odun", "Yeşil"]),
            TabooWord(goalWord: "Tatlı", tabooWords: ["Şeker", "Yemek", "Pasta", "Tat", "Meyve"]),
            TabooWord(goalWord: "Müzik", tabooWords: ["Şarkı", "Nota", "Enstrüman", "Melodi", "Dinlemek"]),
            TabooWord(goalWord: "Şarkı", tabooWords: ["Müzik", "Melodi", "Söylemek", "Nota", "Sanatçı"]),
            TabooWord(goalWord: "Nota", tabooWords: ["Müzik", "Şarkı", "Enstrüman", "Yazmak", "Melodi"]),
            TabooWord(goalWord: "Enstrüman", tabooWords: ["Müzik", "Çalmak", "Gitar", "Piyano", "Ses"]),
            TabooWord(goalWord: "Melodi", tabooWords: ["Müzik", "Şarkı", "Nota", "Ritim", "Dinlemek"]),
            TabooWord(goalWord: "Dinlemek", tabooWords: ["Müzik", "Ses", "Kulak", "Şarkı", "Duyma"]),
            TabooWord(goalWord: "Film", tabooWords: ["Sinema", "Oyuncu", "Yönetmen", "Sahne", "Ekran"]),
            TabooWord(goalWord: "Sinema", tabooWords: ["Film", "Ekran", "Oyuncu", "Koltuk", "Yönetmen"]),
            TabooWord(goalWord: "Oyuncu", tabooWords: ["Film", "Tiyatro", "Rol", "Sahne", "Karakter"]),
            TabooWord(goalWord: "Yönetmen", tabooWords: ["Film", "Sinema", "Sahne", "Çekim", "Senaryo"]),
            TabooWord(goalWord: "Sahne", tabooWords: ["Tiyatro", "Film", "Oyuncu", "Performans", "Gösteri"]),
            TabooWord(goalWord: "Çiçek", tabooWords: ["Renk", "Koku", "Yaprak", "Bahçe", "Papatya"]),
            TabooWord(goalWord: "Renk", tabooWords: ["Boya", "Göz", "Kırmızı", "Mavi", "Palet"]),
            TabooWord(goalWord: "Koku", tabooWords: ["Burun", "Parfüm", "Güzel", "Koklamak", "Çiçek"]),
            TabooWord(goalWord: "Yaprak", tabooWords: ["Ağaç", "Bitki", "Yeşil", "Sonbahar", "Dal"]),
            TabooWord(goalWord: "Bahçe", tabooWords: ["Bitki", "Çiçek", "Ağaç", "Meyve", "Sebze"]),
            TabooWord(goalWord: "Papatya", tabooWords: ["Çiçek", "Beyaz", "Sarı", "Bahçe", "Buket"]),
            TabooWord(goalWord: "Araba", tabooWords: ["Tekerlek", "Motor", "Yol", "Direksiyon", "Benzin"]),
            TabooWord(goalWord: "Tekerlek", tabooWords: ["Araba", "Bisiklet", "Dönmek", "Lastik", "Yol"]),
            TabooWord(goalWord: "Motor", tabooWords: ["Araba", "Güç", "Makine", "Benzin", "Çalıştırmak"]),
            TabooWord(goalWord: "Yol", tabooWords: ["Araç", "Asfalt", "Sürmek", "Seyahat", "Trafik"]),
            TabooWord(goalWord: "Direksiyon", tabooWords: ["Araba", "Sürmek", "Kontrol", "Yol", "Şoför"]),
            TabooWord(goalWord: "Benzin", tabooWords: ["Yakıt", "Araba", "Depo", "İstasyon", "Motor"]),
            TabooWord(goalWord: "Telefon", tabooWords: ["Aramak", "Mesaj", "Konuşmak", "Akıllı", "Ekran"]),
            TabooWord(goalWord: "Aramak", tabooWords: ["Telefon", "Bulmak", "Konuşmak", "Numara", "Çağrı"]),
            TabooWord(goalWord: "Mesaj", tabooWords: ["Telefon", "Yazmak", "Göndermek", "SMS", "İletişim"]),
            TabooWord(goalWord: "Konuşmak", tabooWords: ["Ses", "Sohbet", "Telefon", "Dil", "İletişim"]),
            TabooWord(goalWord: "Akıllı", tabooWords: ["Teknoloji", "Telefon", "Zeki", "İnternet", "Ekran"]),
            TabooWord(goalWord: "Ekran", tabooWords: ["Telefon", "Bilgisayar", "Görüntü", "Televizyon", "Dokunmatik"]),
            TabooWord(goalWord: "Bilgisayar", tabooWords: ["Klavye", "Ekran", "Fare", "Program", "İnternet"]),
            TabooWord(goalWord: "Futbol", tabooWords: ["Top", "Saha", "Gol", "Kale", "Maç"]),
            TabooWord(goalWord: "Top", tabooWords: ["Oyun", "Yuvarlak", "Futbol", "Basketbol", "Voleybol"]),
            TabooWord(goalWord: "Saha", tabooWords: ["Oyun", "Futbol", "Spor", "Çim", "Maç"]),
            TabooWord(goalWord: "Gol", tabooWords: ["Futbol", "Kale", "Maç", "Skor", "Atmak"]),
            TabooWord(goalWord: "Kale", tabooWords: ["Futbol", "Gol", "Kaleci", "Savunma", "Maç"]),
            TabooWord(goalWord: "Maç", tabooWords: ["Futbol", "Takım", "Saha", "Gol", "Hakem"]),
            TabooWord(goalWord: "Mont", tabooWords: ["Kış", "Soğuk", "Giysi", "Ceket", "Dış Giyim"]),
            TabooWord(goalWord: "Eşofman", tabooWords: ["Spor", "Koşu", "Rahat", "Giysi", "Antrenman"]),
            TabooWord(goalWord: "Kot", tabooWords: ["Pantolon", "Jean", "Mavi", "Giysi", "Moda"]),
            TabooWord(goalWord: "Pantolon", tabooWords: ["Giysi", "Bacak", "Bel", "Ceket", "Kemer"]),
            TabooWord(goalWord: "Villa", tabooWords: ["Ev", "Bahçe", "Lüks", "Yazlık", "Bina"]),
            TabooWord(goalWord: "Otel", tabooWords: ["Konaklama", "Tatil", "Oda", "Resepsiyon", "Yatak"]),
            TabooWord(goalWord: "Okyanus", tabooWords: ["Deniz", "Büyük", "Su", "Dalga", "Mavi"]),
            TabooWord(goalWord: "Beste", tabooWords: ["Müzik", "Şarkı", "Nota", "Kompozisyon", "Yaratmak"]),
            TabooWord(goalWord: "Şarkı", tabooWords: ["Müzik", "Söz", "Melodi", "Dinlemek", "Nota"]),
            TabooWord(goalWord: "Beşer", tabooWords: ["İnsan", "Birey", "Toplum", "Kişi", "Canlı"]),
            TabooWord(goalWord: "İnsan", tabooWords: ["Birey", "Beşer", "Canlı", "Toplum", "Kişi"]),
            TabooWord(goalWord: "Beyazlatıcı", tabooWords: ["Deterjan", "Çamaşır", "Temizlik", "Leke", "Renk"]),
            TabooWord(goalWord: "Deterjan", tabooWords: ["Temizlik", "Çamaşır", "Beyazlatıcı", "Leke", "Sabun"]),
            TabooWord(goalWord: "Peynir", tabooWords: ["Süt", "Kahvaltı", "Beyaz", "Gıda", "Kaşar"]),
            TabooWord(goalWord: "Bezdirmek", tabooWords: ["Bıktırmak", "Sıkmak", "Yorulmak", "Rahatsız Etmek", "Yormak"]),
            TabooWord(goalWord: "Beyin", tabooWords: ["Zihin", "Düşünce", "Sinir", "Organ", "Kafa"]),
            TabooWord(goalWord: "Beton", tabooWords: ["Çimento", "Yapı", "İnşaat", "Katı", "Malzeme"]),
            TabooWord(goalWord: "Sarımsak", tabooWords: ["Koku", "Yemek", "Beyaz", "Sebze", "Tat"]),
            TabooWord(goalWord: "Soğan", tabooWords: ["Yemek", "Sebze", "Gözyaşı", "Kokmak", "Beyaz"]),
            TabooWord(goalWord: "Biber", tabooWords: ["Sebze", "Baharat", "Acı", "Yeşil", "Tat"]),
            TabooWord(goalWord: "Lahmacun", tabooWords: ["Yemek", "Et", "Türk", "Fırın", "Döner"]),
            TabooWord(goalWord: "Kebap", tabooWords: ["Et", "Mersin", "Tavuk", "Lavaş", "Baharat"]),
            TabooWord(goalWord: "Tantuni", tabooWords: ["Et", "Yemek", "Türk", "Ekmek", "Baharat"]),
            TabooWord(goalWord: "Kız Kulesi", tabooWords: ["İstanbul", "Deniz", "Tarih", "Efsane", "Ada"]),
            TabooWord(goalWord: "Kız Kalesi", tabooWords: ["Mersin", "Deniz", "Tarih", "Efsane", "Ada"]),
            TabooWord(goalWord: "Peri Bacaları", tabooWords: ["Kapadokya", "Tarih", "Doğa", "Turizm", "Yeryüzü Şekilleri"]),
            TabooWord(goalWord: "Kayak Yapmak", tabooWords: ["Kar", "Spor", "Kış", "Dağ", "Pist"]),
            TabooWord(goalWord: "Sucuk Ekmek", tabooWords: ["Yemek", "Et", "Ekmek", "Sandviç", "Türk"]),
            TabooWord(goalWord: "Yumurta", tabooWords: ["Tavuk", "Kahvaltı", "Beyaz", "Protein", "Yemek"]),
            TabooWord(goalWord: "Antik Kent", tabooWords: ["Tarih", "Harabe", "Kazı", "Roma", "Şehir"]),
            TabooWord(goalWord: "Boğaz Köprüsü", tabooWords: ["İstanbul", "Boğaz", "Asma", "Trafik", "Köprü"]),
            TabooWord(goalWord: "Galata Kulesi", tabooWords: ["İstanbul", "Tarih", "Manzara", "Beyoğlu", "Kule"]),
            TabooWord(goalWord: "Barbar", tabooWords: ["Vahşi", "Savaşçı", "Kaba", "İlkel", "Gaddar"]),
            TabooWord(goalWord: "Müdür", tabooWords: ["Şef", "Yönetici", "Okul", "Başkan", "Amir"]),
            TabooWord(goalWord: "Beceri", tabooWords: ["Yetenek", "Maharet", "Hüner", "Uzmanlık", "Kabiliyet"]),
            TabooWord(goalWord: "Bebek", tabooWords: ["Çocuk", "Küçük", "Yeni Doğan", "Minik", "Ağlamak"]),
            TabooWord(goalWord: "Bazlama", tabooWords: ["Ekmek", "Pişmek", "Hamur", "Gözleme", "Yufka"]),
            TabooWord(goalWord: "Bayrak", tabooWords: ["Sancak", "Ulusal", "Dalgalanmak", "Ülke", "Renk"]),
            TabooWord(goalWord: "Baykuş", tabooWords: ["Kuş", "Gece", "Uğursuz", "Gözler", "Kanat"]),
            TabooWord(goalWord: "Mantar", tabooWords: ["Sote", "Orman", "Yemek", "Zehirli", "Kültür"]),
            TabooWord(goalWord: "Becerikli", tabooWords: ["Yetenekli", "Maharetli", "Hünerli", "Uzman", "Başarılı"]),
            TabooWord(goalWord: "Beceriksiz", tabooWords: ["Yeteneksiz", "Maharetsiz", "Başarısız", "Sakar", "Kabiliyetsiz"]),
            TabooWord(goalWord: "Bere", tabooWords: ["Şapka", "Soğuk", "Yün", "Kış", "Baş"]),
            TabooWord(goalWord: "Atkı", tabooWords: ["Boyun", "Kış", "Yün", "Soğuk", "Kumaş"]),
            TabooWord(goalWord: "Yıldız", tabooWords: ["Gök", "Gece", "Parlamak", "Gökyüzü", "Işık"]),
            TabooWord(goalWord: "Enerji", tabooWords: ["Güç", "Elektrik", "Yenilenebilir", "Yakıt", "Hareket"]),
            TabooWord(goalWord: "Meteor", tabooWords: ["Göktaşı", "Uzay", "Düşmek", "Atmosfer", "Çarpma"]),
            TabooWord(goalWord: "Cüce", tabooWords: ["Küçük", "Kısa", "Masal", "Kısa Boylu", "Minik"]),
            TabooWord(goalWord: "Şirinler", tabooWords: ["Çizgi Film", "Mavi", "Gargamel", "Köy", "Papa Şirin"]),
            TabooWord(goalWord: "Radyo", tabooWords: ["FM", "Yayın", "Dinlemek", "Ses", "Müzik"]),
            TabooWord(goalWord: "Uranüs", tabooWords: ["Gezegen", "Güneş Sistemi", "Mavi", "Atmosfer", "Çevrim"]),
            TabooWord(goalWord: "Uzaylı", tabooWords: ["Dünya Dışı", "Mars", "Yaratık", "Bilim Kurgu", "UFO"]),
            TabooWord(goalWord: "Venüs", tabooWords: ["Gezegen", "Aşk Tanrıçası", "Güneş Sistemi", "Parlak", "Atmosfer"]),
            TabooWord(goalWord: "Bone", tabooWords: ["Baş", "Yüzmek", "Kapak", "Saç", "Duş"]),
            TabooWord(goalWord: "Ay ışığı", tabooWords: ["Gece", "Ay", "Parlak", "Gökyüzü", "Doğa"]),
            TabooWord(goalWord: "Güneş", tabooWords: ["Işık", "Isı", "Gök", "Gündüz", "Yıldız"]),
            TabooWord(goalWord: "Satürn", tabooWords: ["Gezegen", "Halkalar", "Güneş Sistemi", "Gaz", "Astronomi"]),
            TabooWord(goalWord: "Neptün", tabooWords: ["Gezegen", "Mavi", "Uzak", "Güneş Sistemi", "Astronomi"]),
            TabooWord(goalWord: "Jüpiter", tabooWords: ["Gezegen", "Büyük", "Gaz", "Güneş Sistemi", "Kırmızı Nokta"]),
            TabooWord(goalWord: "Merkür", tabooWords: ["Gezegen", "Güneşe En Yakın", "Küçük", "Güneş Sistemi", "Astronomi"]),
            TabooWord(goalWord: "Uzay", tabooWords: ["Boşluk", "Yıldızlar", "Galaksi", "Astronomi", "Sonsuz"]),
            TabooWord(goalWord: "Astronomi", tabooWords: ["Bilim", "Uzay", "Gezegenler", "Yıldızlar", "Teleskop"]),
            TabooWord(goalWord: "Astrolog", tabooWords: ["Burç", "Yıldız", "Gelecek", "Fal", "Horoskop"]),
            TabooWord(goalWord: "Galaksi", tabooWords: ["Yıldızlar", "Uzay", "Samanyolu", "Evren", "Gökada"]),
            TabooWord(goalWord: "Gök taşı", tabooWords: ["Meteor", "Uzay", "Düşmek", "Atmosfer", "Çarpma"]),
            TabooWord(goalWord: "Güneş tutulması", tabooWords: ["Ay", "Gökyüzü", "Astronomi", "Karanlık", "Yörünge"]),
            TabooWord(goalWord: "Ay tutulması", tabooWords: ["Güneş", "Gökyüzü", "Astronomi", "Karanlık", "Yörünge"]),
            TabooWord(goalWord: "Kara delik", tabooWords: ["Uzay", "Çekim", "Evren", "Astronomi", "Yıldız"]),
            TabooWord(goalWord: "Klima", tabooWords: ["Soğutma", "Isıtma", "Cihaz", "Hava", "Elektrik"]),
            TabooWord(goalWord: "Soba", tabooWords: ["Isıtma", "Kış", "Odun", "Kömür", "Ev"]),
            TabooWord(goalWord: "Kumpir", tabooWords: ["Patates", "Fırın", "Tereyağı", "Kaşar", "Yemek"]),
            TabooWord(goalWord: "Hamburger", tabooWords: ["Ekmek", "Et", "Marul", "Sos", "Fast food"]),
            TabooWord(goalWord: "Pizza", tabooWords: ["Hamur", "Peynir", "Domates", "Fırın", "Yemek"]),
            TabooWord(goalWord: "Siyah", tabooWords: ["Renk", "Koyu", "Gölge", "Beyaz", "Gece"]),
            TabooWord(goalWord: "Espresso", tabooWords: ["Kahve", "İtalya", "Çekirdek", "Makine", "Shot"]),
            TabooWord(goalWord: "Latte", tabooWords: ["Kahve", "Süt", "Espresso", "Köpük", "Kafe"]),
            TabooWord(goalWord: "Sarj", tabooWords: ["Pil", "Elektrik", "Kablo", "Telefon", "Batarya"]),
            TabooWord(goalWord: "Kek", tabooWords: ["Tatlı", "Pasta", "Fırın", "Un", "Çikolata"]),
            TabooWord(goalWord: "Pasta", tabooWords: ["Tatlı", "Doğum günü", "Krema", "Dilim", "Yemek"]),
            TabooWord(goalWord: "Yakamoz", tabooWords: ["Gece", "Deniz", "Parıltı", "Ay", "Işık"]),
            TabooWord(goalWord: "Ay", tabooWords: ["Gökyüzü", "Gece", "Uydusu", "Işık", "Astronomi"]),
            TabooWord(goalWord: "Yatmak", tabooWords: ["Yatak", "Uyku", "Gece", "Gündüz", "Dinlenmek"]),
            TabooWord(goalWord: "Yatak", tabooWords: ["Yat", "Uyku", "Gece", "Gündüz", "Odası"]),
            TabooWord(goalWord: "Uyku", tabooWords: ["Yat", "Yatak", "Gece", "Gündüz", "Rüya"]),
            TabooWord(goalWord: "Gece", tabooWords: ["Gündüz", "Ay", "Yıldızlar", "Karanlık", "Işık"]),
            TabooWord(goalWord: "Gündüz", tabooWords: ["Gece", "Güneş", "Aydınlık", "Çalışma", "Aktivite"]),
            TabooWord(goalWord: "Köfte", tabooWords: ["Kıyma", "Izgara", "Yemek", "Pilav", "Şiş"]),
            TabooWord(goalWord: "Ekmek", tabooWords: ["Un", "Fırın", "Dilim", "Yemek", "Somun"]),
            TabooWord(goalWord: "Kaymak", tabooWords: ["Sürmek", "Krem", "Süt", "Kahvaltı", "Tatlı"]),
            TabooWord(goalWord: "Sürmek", tabooWords: ["Kaymak", "Araç", "Yol", "Krem", "Yağ"]),
            TabooWord(goalWord: "Gezmek", tabooWords: ["Seyahat", "Tatil", "Şehir", "Turist", "Keşfetmek"]),
            TabooWord(goalWord: "Makarna", tabooWords: ["Spagetti", "Pişirmek", "İtalyan", "Sos", "Yemek"]),
            TabooWord(goalWord: "Monitör", tabooWords: ["Ekran", "Bilgisayar", "Görüntü", "Fare", "Klavye"]),
            TabooWord(goalWord: "Balina", tabooWords: ["Deniz", "Büyük", "Memeli", "Sualtı", "Balık"]),
            TabooWord(goalWord: "Yunus", tabooWords: ["Deniz", "Balık", "Mavi", "Şov", "Akvaryum"]),
            TabooWord(goalWord: "Hamsi", tabooWords: ["Balık", "Karadeniz", "Küçük", "Taze", "Pişirmek"]),
            TabooWord(goalWord: "Sözlük", tabooWords: ["Kelime", "Anlam", "Tanım", "Kitap", "Bilgi"]),
            TabooWord(goalWord: "Duygu", tabooWords: ["Hiss", "Kalp", "Mutluluk", "Üzüntü", "Sevgi"]),
            TabooWord(goalWord: "Üzüntü", tabooWords: ["Hüzün", "Sıkıntı", "Depresyon", "Mutsuzluk", "Acı"]),
            TabooWord(goalWord: "Neşe", tabooWords: ["Mutluluk", "Gülmek", "Keyif", "Eğlence", "Coşku"]),
            TabooWord(goalWord: "Sevinç", tabooWords: ["Mutluluk", "Kutlama", "Heyecan", "Neşe", "Sevgi"]),
            TabooWord(goalWord: "Balta", tabooWords: ["Ağaç", "Kesmek", "Orman", "Tahta", "Kaba"]),
            TabooWord(goalWord: "Kılıç", tabooWords: ["Silah", "Savaş", "Kesmek", "Kılıf", "Çelik"]),
            TabooWord(goalWord: "Silah", tabooWords: ["Tüfek", "Tabanca", "Mermi", "Asker", "Güç"]),
            TabooWord(goalWord: "Havuz", tabooWords: ["Yüzme", "Su", "Kenar", "Bahçe", "Derin"]),
            TabooWord(goalWord: "Kano", tabooWords: ["Su", "Kürek", "Tekne", "Akarsu", "Spor"]),
            TabooWord(goalWord: "Kayık", tabooWords: ["Su", "Tekne", "Kürek", "Balıkçı", "Göl"]),
            TabooWord(goalWord: "Gemi", tabooWords: ["Deniz", "Yolculuk", "Liman", "Gemici", "Yük"]),
            TabooWord(goalWord: "Abartmak", tabooWords: ["Fazla", "Değer", "İfade", "Dikkat", "Gösteriş"]),
            TabooWord(goalWord: "Abaküs", tabooWords: ["Sayı", "Hesap", "Tahta", "Toplama", "Çarpma"]),
            TabooWord(goalWord: "Bacak", tabooWords: ["İnsan", "Yürümek", "Uzun", "Kas", "Ayak"]),
            TabooWord(goalWord: "Badana", tabooWords: ["Boya", "Duvar", "Renk", "Tamir", "Eski"]),
            TabooWord(goalWord: "Baba", tabooWords: ["Aile", "Erkek", "Baba", "Babaanne", "Anne"]),
            TabooWord(goalWord: "Babet", tabooWords: ["Ayak", "Kadın", "Topuklu", "Balerin", "Rahat"]),
            TabooWord(goalWord: "Bağırsak", tabooWords: ["Sindirim", "Organ", "İnce", "Kalın", "Sağlık"]),
            TabooWord(goalWord: "Kokoreç", tabooWords: ["İç", "Mide", "Kuzu", "Pişirmek", "Lezzet"]),
            TabooWord(goalWord: "Sucuk", tabooWords: ["Et", "Kırmızı", "Köfte", "Baharat", "Pişirmek"]),
            TabooWord(goalWord: "Bağlaç", tabooWords: ["Cümle", "Birleştirme", "Bağlantı", "Dil", "Kelime"]),
            TabooWord(goalWord: "Sabır", tabooWords: ["Bekleme", "Özveri", "Sakin", "Dayanma", "Zaman"]),
            TabooWord(goalWord: "Trip", tabooWords: ["Seyahat", "Gezi", "Yolculuk", "Uyuşturucu", "Hiss"]),
            TabooWord(goalWord: "Şans", tabooWords: ["Kader", "Başarı", "Sansür", "Talih", "Şanslı"]),
            TabooWord(goalWord: "Aşk", tabooWords: ["Sevgi", "Duygu", "Kalp", "İlişki", "Romantik"]),
            TabooWord(goalWord: "Papatya", tabooWords: ["Çiçek", "Beyaz", "Sarı", "Yaprak", "Aşk"]),
            TabooWord(goalWord: "İnternet", tabooWords: ["Bağlantı", "Bilgi", "Web", "Teknoloji", "Site"]),
            TabooWord(goalWord: "Örümcek", tabooWords: ["Örümcek", "Dokuma", "Köşe", "Ağ", "Zehir"]),
            TabooWord(goalWord: "Maymun", tabooWords: ["Hayvan", "Orman", "Ağaç", "Akrobat", "İnsan"]),
            TabooWord(goalWord: "Ayı", tabooWords: ["Hayvan", "Orman", "Kış", "Büyük", "Kuvvet"]),
            TabooWord(goalWord: "Karınca", tabooWords: ["Küçük", "Toprak", "Yemek", "Çalışma", "Koloni"]),
            TabooWord(goalWord: "Ağustos", tabooWords: ["Yaz", "Sıcak", "Ay", "Tatil", "Doğum günü"]),
            TabooWord(goalWord: "Haziran", tabooWords: ["Yaz", "Sıcak", "Ay", "Tatil", "Doğum günü"]),
            TabooWord(goalWord: "Zıtlaşmak", tabooWords: ["Tartışma", "Fikir", "Anlaşmazlık", "Karşı", "Uyum"]),
            TabooWord(goalWord: "Boğa", tabooWords: ["Hayvan", "Boynuz", "Tarla", "Güç", "Büyük"]),
            TabooWord(goalWord: "Boyoz", tabooWords: ["Tatlı", "Kahvaltı", "Hamur", "Un", "Yağ"]),
            TabooWord(goalWord: "Kumru", tabooWords: ["Kuş", "Göç", "Yuva", "Ekmek", "Gelincik"]),
            TabooWord(goalWord: "Tost", tabooWords: ["Ekmek", "Peynir", "Sıcak", "Kızartmak", "Sandviç"]),
            TabooWord(goalWord: "Müzik", tabooWords: ["Nota", "Enstrüman", "Dinlemek", "Melodi", "Ritim"]),
            TabooWord(goalWord: "Kader", tabooWords: ["Baht", "Hayat", "Yol", "Önceden", "Belirleme"]),
            TabooWord(goalWord: "Kısmet", tabooWords: ["Kader", "Baht", "Ön", "Kutlu", "Yol"]),
            TabooWord(goalWord: "Yüzük", tabooWords: ["Parmak", "Takı", "Altın", "Nişan", "Evlenmek"]),
            TabooWord(goalWord: "Küpe", tabooWords: ["Takı", "Kulak", "Altın", "Kadın", "Pırlanta"]),
            TabooWord(goalWord: "Kemer", tabooWords: ["Kıyafet", "Pantolon", "Bel", "Deri", "Kemer"]),
            TabooWord(goalWord: "Bileklik", tabooWords: ["Takı", "El", "Altın", "Deri", "Renkli"]),
            TabooWord(goalWord: "Bilezik", tabooWords: ["Takı", "El", "Altın", "Gümüş", "Pırlanta"]),
            TabooWord(goalWord: "Bandana", tabooWords: ["Baş", "Eşarp", "Desen", "Kumaş", "Stil"]),
            TabooWord(goalWord: "Tişört", tabooWords: ["Üst", "Giyim", "Kol", "Rahat", "Pamuklu"]),
            TabooWord(goalWord: "Şort", tabooWords: ["Alt", "Giyim", "Kısa", "Rahat", "Pamuklu"]),
            TabooWord(goalWord: "Kıyafet", tabooWords: ["Giyim", "Moda", "Stil", "Renk", "Kumaş"]),
            TabooWord(goalWord: "Kutu", tabooWords: ["Paket", "Karton", "Hediye", "Depo", "Kutu"]),
            TabooWord(goalWord: "Gömlek", tabooWords: ["Üst", "Giyim", "Düğme", "Kol", "Ofis"]),
            TabooWord(goalWord: "Gelinlik", tabooWords: ["Düğün", "Gelin", "Elbise", "Beyaz", "Gelinlik"]),
            TabooWord(goalWord: "Gelin", tabooWords: ["Düğün", "Evlilik", "Gelinlik", "Damad", "Mutluluk"]),
            TabooWord(goalWord: "Mouse", tabooWords: ["Bilgisayar", "Tıklama", "Kurulum", "Fare", "Kablosuz"]),
            TabooWord(goalWord: "Klavye", tabooWords: ["Bilgisayar", "Tuş", "Yazı", "Kullanmak", "QWERTY"]),
            TabooWord(goalWord: "Kulaklık", tabooWords: ["Ses", "Dinlemek", "Kulak", "Müzik", "Telefon"]),
            TabooWord(goalWord: "Kafa", tabooWords: ["Baş", "Zihin", "Düşünmek", "Kafa", "Beyin"]),
            TabooWord(goalWord: "Saç", tabooWords: ["Baş", "Kafa", "Tarak", "Kuaför", "Rengi"]),
            TabooWord(goalWord: "Bikini", tabooWords: ["Mayo", "Plaj", "Kadın", "Deniz", "Yüzme"]),
            TabooWord(goalWord: "Mayo", tabooWords: ["Deniz", "Plaj", "Erkek", "Kadın", "Yüzme"]),
            TabooWord(goalWord: "Balık", tabooWords: ["Deniz", "Su", "Yüzgeç", "Somon", "Lezzet"]),
            TabooWord(goalWord: "Bandaj", tabooWords: ["Yara", "Sargı", "Hastane", "Sağlık", "Kırık"]),
            TabooWord(goalWord: "Bal", tabooWords: ["Tatlı", "Arı", "Şeker", "Kovan", "Ballı"]),
            TabooWord(goalWord: "Badem", tabooWords: ["Kuruyemiş", "Ağaç", "Kabuklu", "Lezzet", "Enerji"]),
            TabooWord(goalWord: "Fıstık", tabooWords: ["Kuruyemiş", "Ağaç", "Kabuklu", "Antep", "Lezzet"]),
            TabooWord(goalWord: "Balmumu", tabooWords: ["Balmumu", "Ağaç", "Koruma", "Sert", "Balmumu"]),
            TabooWord(goalWord: "Mum", tabooWords: ["Alev", "Parafin", "Koku", "Işık", "Yanmak"]),
            TabooWord(goalWord: "Laptop", tabooWords: ["Bilgisayar", "Taşınabilir", "Ekran", "Klavye", "İşlemci"]),
            TabooWord(goalWord: "Kartlık", tabooWords: ["Kart", "Cüzdan", "Kredi", "Para", "Banka"]),
            TabooWord(goalWord: "Cüzdan", tabooWords: ["Para", "Kartlık", "Kredi", "Cüzdan", "Deri"]),
            TabooWord(goalWord: "Uçurma", tabooWords: ["Uçmak", "Gökyüzü", "Rüzgar", "Kumanda", "Çocuk"]),
            TabooWord(goalWord: "Ufak", tabooWords: ["Küçük", "Minik", "Dar", "Bebek", "Kısacık"]),
            TabooWord(goalWord: "Ufo", tabooWords: ["Uzaylı", "Gemi", "Dünya dışı", "Gizem", "Gökyüzü"]),
            TabooWord(goalWord: "Cadı", tabooWords: ["Büyü", "Süpürge", "Şapka", "Kötü", "Sihir"]),
            TabooWord(goalWord: "Un", tabooWords: ["Ekmek", "Hamur", "Fırın", "Beyaz", "Malzeme"]),
            TabooWord(goalWord: "Helva", tabooWords: ["Tatlı", "İrmik", "Şeker", "Türk", "Lezzet"]),
            TabooWord(goalWord: "Melek", tabooWords: ["Kanat", "Cennet", "Beyaz", "Gökyüzü", "Masum"]),
            TabooWord(goalWord: "Şeytan", tabooWords: ["Kötü", "Ateş", "Kırmızı", "Günah", "Cin"]),
            TabooWord(goalWord: "Pahalı", tabooWords: ["Para", "Değerli", "Lüks", "Maliyetli", "Fiyat"]),
            TabooWord(goalWord: "Ucuz", tabooWords: ["Ekonomik", "Hesaplı", "Maliyet", "Fiyat", "Uygun"]),
            TabooWord(goalWord: "Çukur", tabooWords: ["Derin", "Kazmak", "Hendek", "Kuyu", "Açık"]),
            TabooWord(goalWord: "Kuyu", tabooWords: ["Su", "Derin", "Çukur", "Kazmak", "Kova"]),
            TabooWord(goalWord: "Teneke", tabooWords: ["Metal", "Kutu", "İçmek", "Konserve", "Ambalaj"]),
            TabooWord(goalWord: "Sehpa", tabooWords: ["Masa", "Ayak", "Mobilya", "Salon", "Yüzey"]),
            TabooWord(goalWord: "Ulumak", tabooWords: ["Kurt", "Ses", "Gece", "Ay", "Hayvan"]),
            TabooWord(goalWord: "Kurt", tabooWords: ["Hayvan", "Orman", "Ulumak", "Yırtıcı", "Sürü"]),
            TabooWord(goalWord: "Böcek", tabooWords: ["Küçük", "Haşere", "Karınca", "Doğa", "Canlı"]),
            TabooWord(goalWord: "Duvar", tabooWords: ["Ev", "Yapı", "Tuğla", "Beton", "Bina"]),
            TabooWord(goalWord: "Kablo", tabooWords: ["Elektrik", "Bağlantı", "Tel", "Uzun", "Plastik"]),
            TabooWord(goalWord: "Mikrofon", tabooWords: ["Ses", "Konuşma", "Şarkı", "Kayıt", "Cihaz"]),
            TabooWord(goalWord: "Mercek", tabooWords: ["Gözlük", "Büyütmek", "Optik", "Lens", "Göz"]),
            TabooWord(goalWord: "Mikroskop", tabooWords: ["Büyütmek", "Laboratuvar", "Bilim", "Cam", "Gözlem"]),
            TabooWord(goalWord: "Kolonya", tabooWords: ["Koku", "Limon", "Alkol", "Temizlik", "Elleri"]),
            TabooWord(goalWord: "Parfüm", tabooWords: ["Koku", "Şişe", "Sprey", "Kadın", "Erkek"]),
            TabooWord(goalWord: "Terlik", tabooWords: ["Ayak", "Ev", "Giymek", "Rahat", "Yumuşak"]),
            TabooWord(goalWord: "Kapı", tabooWords: ["Açmak", "Kapatmak", "Giriş", "Çıkış", "Kilit"]),
            TabooWord(goalWord: "Kapı kolu", tabooWords: ["Kapı", "Tutmak", "Açmak", "Kapatmak", "Kilit"]),
            TabooWord(goalWord: "Anahtar", tabooWords: ["Kilit", "Kapı", "Açmak", "Kapatmak", "Metal"]),
            TabooWord(goalWord: "Ayna", tabooWords: ["Yansımak", "Cam", "Görmek", "Yüz", "Banyo"]),
            TabooWord(goalWord: "Musluk", tabooWords: ["Su", "Açmak", "Kapamak", "Lavabo", "Banyo"]),
            TabooWord(goalWord: "Nehir", tabooWords: ["Su", "Akmak", "Büyük", "Doğa", "Göl"]),
            TabooWord(goalWord: "Dere", tabooWords: ["Su", "Küçük", "Akmak", "Doğa", "Köy"]),
            TabooWord(goalWord: "Mangal", tabooWords: ["Et", "Izgara", "Ateş", "Piknik", "Kömür"]),
            TabooWord(goalWord: "Pirzola", tabooWords: ["Et", "Kuzu", "Izgara", "Yemek", "Kemik"]),
            TabooWord(goalWord: "Van gölü", tabooWords: ["Su", "Büyük", "Doğa", "Türkiye", "Şehir"]),
            TabooWord(goalWord: "Canavar", tabooWords: ["Korku", "Büyük", "Kötü", "Film", "Hayvan"]),
            TabooWord(goalWord: "Video", tabooWords: ["Görüntü", "Kayıt", "Film", "YouTube", "İzlemek"]),
            TabooWord(goalWord: "Basketbol", tabooWords: ["Spor", "Top", "Pot", "Saha", "NBA"]),
            TabooWord(goalWord: "Futbol", tabooWords: ["Top", "Gol", "Saha", "Takım", "Maç"]),
            TabooWord(goalWord: "Hentbol", tabooWords: ["Top", "El", "Saha", "Maç", "Gol"]),
            TabooWord(goalWord: "Voleybol", tabooWords: ["Top", "Saha", "Ağ", "Set", "Maç"]),
            TabooWord(goalWord: "Hokey", tabooWords: ["Buz", "Sopa", "Puck", "Maç", "Gol"]),
            TabooWord(goalWord: "Tenis", tabooWords: ["Raket", "Top", "Saha", "Set", "Maç"]),
            TabooWord(goalWord: "Plaj Voleybolu", tabooWords: ["Kum", "Top", "Saha", "Ağ", "Maç"]),
            TabooWord(goalWord: "Alışveriş", tabooWords: ["Mağaza", "Para", "Satın almak", "Market", "Ürün"]),
            TabooWord(goalWord: "Dolar", tabooWords: ["Para", "ABD", "Kur", "Banka", "Yeşil"]),
            TabooWord(goalWord: "Çorap", tabooWords: ["Ayak", "Giyim", "Pamuk", "Renk", "Çift"]),
            TabooWord(goalWord: "Gözlük", tabooWords: ["Göz", "Cam", "Çerçeve", "Lens", "Görmek"]),
            TabooWord(goalWord: "Tekerlek", tabooWords: ["Araç", "Dönmek", "Lastik", "Jant", "Taşıma"]),
            TabooWord(goalWord: "Direksiyon", tabooWords: ["Araç", "Sürmek", "Yön", "Kontrol", "Araba"]),
            TabooWord(goalWord: "Tahtakale", tabooWords: ["İstanbul", "Pazar", "Toptan", "Çarşı", "Alışveriş"]),
            TabooWord(goalWord: "Panik atak", tabooWords: ["Anksiyete", "Kalp", "Nefes", "Korku", "Stres"]),
            TabooWord(goalWord: "Simit", tabooWords: ["Gevrek", "Susam", "Ekmek", "Fırın", "Kahvaltı"]),
            TabooWord(goalWord: "Youtube", tabooWords: ["Video", "İnternet", "Kanal", "İzlemek", "Abone"]),
            TabooWord(goalWord: "Van Gogh", tabooWords: ["Ressam", "Sanat", "Kulak", "Tablo", "Hollanda"]),
            TabooWord(goalWord: "Nalbant", tabooWords: ["At", "Nalı", "Çekiç", "Ayak", "Demir"]),
            TabooWord(goalWord: "Çivi", tabooWords: ["Çekiç", "Metal", "Sabit", "Duvar", "Tahta"]),
            TabooWord(goalWord: "Nazar", tabooWords: ["Mavi", "Göz", "Kıskançlık", "İnanış", "Kötü"]),
            TabooWord(goalWord: "Tershane", tabooWords: ["Gemi", "Yapmak", "Deniz", "Tamir", "Sanayi"]),
            TabooWord(goalWord: "Patoloji", tabooWords: ["Hastalık", "Doku", "Laboratuvar", "Tahlil", "Doktor"]),
            TabooWord(goalWord: "Bilim", tabooWords: ["Deney", "Araştırma", "Teori", "Laboratuvar", "Keşif"]),
            TabooWord(goalWord: "Felek", tabooWords: ["Kader", "Zaman", "Dünya", "Hayat", "Çark"]),
            TabooWord(goalWord: "Abdesthane", tabooWords: ["Camii", "Temizlik", "İbadet", "Su", "Lavabo"]),
            TabooWord(goalWord: "Darp", tabooWords: ["Şiddet", "Vurmak", "Yaralamak", "Kavga", "Zarar"]),
            TabooWord(goalWord: "Gondol", tabooWords: ["Venedik", "Kayık", "Su", "Kürek", "Turist"]),
            TabooWord(goalWord: "Keşkül", tabooWords: ["Tatlı", "Osmanlı", "Fıstık", "Süt", "Pirinç"]),
            TabooWord(goalWord: "Coğrafya", tabooWords: ["Harita", "Dünya", "Ülke", "Dağ", "Nehir"]),
            TabooWord(goalWord: "Flüt", tabooWords: ["Müzik", "Nefes", "Enstrüman", "Ahşap", "Delik"]),
            TabooWord(goalWord: "Klarnet", tabooWords: ["Müzik", "Nefes", "Enstrüman", "Ahşap", "Ağızlık"]),
            TabooWord(goalWord: "Piyano", tabooWords: ["Müzik", "Tuş", "Enstrüman", "Çalmak", "Beyaz"]),
            TabooWord(goalWord: "Gitar", tabooWords: ["Müzik", "Telli", "Enstrüman", "Çalmak", "Akustik"]),
            TabooWord(goalWord: "Keman", tabooWords: ["Müzik", "Yay", "Enstrüman", "Telli", "Orkestra"]),
            TabooWord(goalWord: "Çello", tabooWords: ["Müzik", "Yay", "Enstrüman", "Telli", "Orkestra"]),
            TabooWord(goalWord: "Darbuka", tabooWords: ["Müzik", "Ritim", "Vurmak", "Enstrüman", "Davul"]),
            TabooWord(goalWord: "Bass Gitar", tabooWords: ["Müzik", "Telli", "Enstrüman", "Çalmak", "Bas"]),
            TabooWord(goalWord: "Mesafe", tabooWords: ["Uzaklık", "Yakınlık", "Uzunluk", "Metre", "Kısa"]),
            TabooWord(goalWord: "Vikingler", tabooWords: ["Kuzey", "Savaşçı", "İskandinav", "Tarihi", "Deniz"]),
            TabooWord(goalWord: "Uydu", tabooWords: ["Uzay", "Yörünge", "Dünya", "Gönderme", "Sinema"]),
            TabooWord(goalWord: "Antipatik", tabooWords: ["Sevilmeyen", "Nefret", "İtici", "Soğuk", "Hoşlanmamak"]),
            TabooWord(goalWord: "Kıkırdamak", tabooWords: ["Gülmek", "Ses", "Kahkaha", "Neşeli", "Gülüş"]),
            TabooWord(goalWord: "Şezlong", tabooWords: ["Yatmak", "Plaj", "Güneşlenmek", "Havuz", "Rahat"]),
            TabooWord(goalWord: "Tatil", tabooWords: ["Dinlenme", "Gezi", "Seyahat", "Çalışmak", "Eğlence"]),
            TabooWord(goalWord: "Yazıcı", tabooWords: ["Bilgisayar", "Kağıt", "Çıktı", "Renkli", "Doküman"]),
            TabooWord(goalWord: "Hipnoz", tabooWords: ["Uyku", "Zihin", "Kontrol", "Trans", "Tedavi"]),
            TabooWord(goalWord: "Dumur", tabooWords: ["Şaşkın", "Donmak", "Sarsılmak", "Şok", "Beklenmedik"]),
            TabooWord(goalWord: "Felsefe", tabooWords: ["Düşünce", "Bilim", "Sorgulamak", "Teori", "Sokrat"]),
            TabooWord(goalWord: "Apandisit", tabooWords: ["Karın", "Ağrı", "Ameliyat", "Enfeksiyon", "Appendiks"]),
            TabooWord(goalWord: "Bisküvi", tabooWords: ["Tatlı", "Kuru", "Yemek", "Çay", "Kek"]),
            TabooWord(goalWord: "Sim", tabooWords: ["Parlak", "Süs", "Renkli", "Işıltı", "El işi"]),
            TabooWord(goalWord: "İcra", tabooWords: ["Borç", "Hukuk", "Tahsilat", "Maliye", "Alacak"]),
            TabooWord(goalWord: "Jeoloji", tabooWords: ["Yer", "Bilim", "Deprem", "Kayalar", "Araştırma"]),
            TabooWord(goalWord: "Finans", tabooWords: ["Para", "Banka", "Yatırım", "Ekonomi", "Piyasalar"]),
            TabooWord(goalWord: "Ekonomi", tabooWords: ["Para", "Piyasa", "Finans", "Büyüme", "Enflasyon"]),
            TabooWord(goalWord: "Borsa", tabooWords: ["Hisse", "Piyasa", "Yatırım", "Finans", "Ticaret"]),
            TabooWord(goalWord: "Banka", tabooWords: ["Para", "Finans", "Kredi", "Hesap", "Şube"]),
            TabooWord(goalWord: "Mail", tabooWords: ["E-posta", "Bilgisayar", "İletişim", "Mesaj", "Gmail"]),
            TabooWord(goalWord: "Şalvar", tabooWords: ["Giysi", "Pantolon", "Geleneksel", "Köy", "Bol"]),
            TabooWord(goalWord: "Sicil", tabooWords: ["Kayıt", "Sabıka", "Geçmiş", "Adli", "Kimlik"]),
            TabooWord(goalWord: "Hapis", tabooWords: ["Cezaevi", "Mahkum", "Ceza", "Hücre", "Adalet"]),
            TabooWord(goalWord: "Sabıka", tabooWords: ["Suç", "Kayıt", "Geçmiş", "Adli", "Ceza"]),
            TabooWord(goalWord: "Makyaj", tabooWords: ["Ruj", "Fondöten", "Yüz", "Güzellik", "Makyaj malzemesi"]),
            TabooWord(goalWord: "Damar", tabooWords: ["Kan", "Vücut", "Atardamar", "Toplardamar", "İnsan"]),
            TabooWord(goalWord: "Güneşlik", tabooWords: ["Güneş", "Araba", "Koruma", "Işık", "Perde"]),
            TabooWord(goalWord: "Tül", tabooWords: ["Perde", "İnce", "Şeffaf", "Kumaş", "Süs"]),
            TabooWord(goalWord: "Perde", tabooWords: ["Pencere", "Kumaş", "Tül", "Gölge", "Evin içi"]),
            TabooWord(goalWord: "Süngü", tabooWords: ["Bıçak", "Silah", "Savaş", "Kılıç", "Asker"]),
            TabooWord(goalWord: "İktidarsız", tabooWords: ["Erkek", "Sağlık", "Sorun", "Cinsellik", "Yetersizlik"]),
            TabooWord(goalWord: "Sarsıntı", tabooWords: ["Deprem", "Şok", "Titreşim", "Sallamak", "Yer hareketi"]),
            TabooWord(goalWord: "Asit", tabooWords: ["Kimya", "Sıvı", "Ph", "Baz", "Tepki"]),
            TabooWord(goalWord: "Hipodrom", tabooWords: ["At yarışı", "Pist", "Seyirci", "Bahis", "Koşu"]),
            TabooWord(goalWord: "İmrenmek", tabooWords: ["Kıskanmak", "Özenmek", "Beğenmek", "Hayran", "İstemek"]),
            TabooWord(goalWord: "Özenmek", tabooWords: ["İmrenmek", "İstemek", "Hayran", "Beğenmek", "Kıskanmak"]),
            TabooWord(goalWord: "Hardal", tabooWords: ["Sos", "Baharat", "Sarı", "Ketçap", "Yemek"]),
            TabooWord(goalWord: "Ketçap", tabooWords: ["Sos", "Domates", "Yemek", "Kırmızı", "Patates"]),
            TabooWord(goalWord: "Mayonez", tabooWords: ["Sos", "Yemek", "Beyaz", "Salata", "Sandviç"]),
            TabooWord(goalWord: "Acı Sos", tabooWords: ["Baharatlı", "Yemek", "Sıcak", "Sos", "Biber"]),
            TabooWord(goalWord: "Kimyacı", tabooWords: ["Kimya", "Bilim", "Laboratuvar", "Deney", "Madde"]),
            TabooWord(goalWord: "Devrim", tabooWords: ["İsyan", "Değişim", "Hareket", "İnkılap", "Tarihi"]),
            TabooWord(goalWord: "Kriz", tabooWords: ["Ekonomi", "Sorun", "Çöküş", "Bunalım", "Problem"]),
            TabooWord(goalWord: "Matematik", tabooWords: ["Sayı", "Hesaplama", "Ders", "Geometri", "Aritmetik"]),
            TabooWord(goalWord: "Fonksiyon", tabooWords: ["Matematik", "Görev", "Çalışmak", "İşlev", "Değişken"]),
            TabooWord(goalWord: "Ders", tabooWords: ["Okul", "Öğretmen", "Öğrenci", "Konu", "Sınıf"]),
            TabooWord(goalWord: "Röportaj", tabooWords: ["Gazete", "Söyleşi", "Konuşmak", "Mülakat", "Muhabir"]),
            TabooWord(goalWord: "Pastırma", tabooWords: ["Et", "Yemek", "Sucuk", "Kuru", "Kahvaltı"]),
            TabooWord(goalWord: "Hard Disk", tabooWords: ["Bilgisayar", "Depolama", "Veri", "Sabit disk", "Hafıza"]),
            TabooWord(goalWord: "Berber", tabooWords: ["Saç", "Tıraş", "Sakal", "Erkek", "Kuaför"]),
            TabooWord(goalWord: "Tehdit", tabooWords: ["Korku", "Uyarı", "Şantaj", "Tehlike", "Cezalandırma"]),
            TabooWord(goalWord: "Yaver", tabooWords: ["Asker", "Subay", "Yardımcı", "Komutan", "Orduda"]),
            TabooWord(goalWord: "Safra Kesesi", tabooWords: ["Karaciğer", "Organ", "Ameliyat", "Taş", "Sindirim"]),
            TabooWord(goalWord: "Tundra", tabooWords: ["Soğuk", "Kuzey", "Bitki", "İklim", "Düzlük"]),
            TabooWord(goalWord: "Yıldırım", tabooWords: ["Gökyüzü", "Elektrik", "Şimşek", "Yağmur", "Hızlı"]),
            TabooWord(goalWord: "Şimşek", tabooWords: ["Yıldırım", "Gökyüzü", "Işık", "Yağmur", "Elektrik"]),
            TabooWord(goalWord: "Elektrik", tabooWords: ["Enerji", "Akım", "Işık", "Kablo", "Elektronik"]),
            TabooWord(goalWord: "Etek", tabooWords: ["Giysi", "Kadın", "Kıyafet", "Moda", "Diz"]),
            TabooWord(goalWord: "Kapris", tabooWords: ["Naz", "İnce", "Hassas", "İstek", "Şımarık"]),
            TabooWord(goalWord: "Sineye Çekmek", tabooWords: ["Kabul etmek", "Tahammül", "Sabır", "Katlanmak", "Sessiz"]),
            TabooWord(goalWord: "Tuzak", tabooWords: ["Kapan", "Pusu", "Tuzağa düşürmek", "Plan", "Yakalamak"]),
            TabooWord(goalWord: "Pusu", tabooWords: ["Gizli", "Beklemek", "Saldırmak", "Tuzak", "Ani"]),
            TabooWord(goalWord: "Koleksiyon", tabooWords: ["Toplamak", "Biriktirmek", "Hobi", "Nadir", "Objeler"]),
            TabooWord(goalWord: "Diyet", tabooWords: ["Yemek", "Kilo", "Sağlık", "Beslenme", "Rejim"]),
            TabooWord(goalWord: "Galaksi", tabooWords: ["Uzay", "Yıldız", "Samanyolu", "Evren", "Astronomi"]),
            TabooWord(goalWord: "Adidas", tabooWords: ["Spor", "Ayakkabı", "Marka", "Giyim", "Nike"]),
            TabooWord(goalWord: "Sade", tabooWords: ["Basit", "Şeker", "Kahve", "Temiz", "Süslü değil"]),
            TabooWord(goalWord: "Parantez", tabooWords: ["Noktalama", "İşaret", "Yazı", "Matematik", "İçinde"]),
            TabooWord(goalWord: "Broşür", tabooWords: ["Tanıtım", "Kağıt", "Bilgi", "Reklam", "Dergi"]),
            TabooWord(goalWord: "Cömert", tabooWords: ["Verici", "Eli açık", "Bağış", "Zengin", "Bolluk"]),
            TabooWord(goalWord: "Balon", tabooWords: ["Uçan", "Helyum", "Şişirmek", "Renkli", "Çocuk"]),
            TabooWord(goalWord: "Gezi", tabooWords: ["Seyahat", "Tur", "Tatil", "Gezmek", "Rehber"]),
            TabooWord(goalWord: "Yazıhane", tabooWords: ["Ofis", "Çalışma", "Büro", "Masa", "İş"]),
            TabooWord(goalWord: "Kese kağıdı", tabooWords: ["Kağıt", "Market", "Taşımak", "Alışveriş", "Çanta"]),
            TabooWord(goalWord: "Mersin", tabooWords: ["Şehir", "Türkiye", "Akdeniz", "Liman", "Narenciye"]),
            TabooWord(goalWord: "Adana", tabooWords: ["Şehir", "Kebap", "Türkiye", "Güney", "Sıcak"]),
            TabooWord(goalWord: "Bitlis", tabooWords: ["Şehir", "Doğu", "Türkiye", "Tarihi", "Kalesi"]),
            TabooWord(goalWord: "Gaziantep", tabooWords: ["Şehir", "Baklava", "Türkiye", "Güneydoğu", "Fıstık"]),
            TabooWord(goalWord: "Antalya", tabooWords: ["Şehir", "Turizm", "Türkiye", "Plaj", "Deniz"]),
            TabooWord(goalWord: "Muğla", tabooWords: ["Şehir", "Ege", "Türkiye", "Turizm", "Bodrum"]),
            TabooWord(goalWord: "İzmir", tabooWords: ["Şehir", "Ege", "Türkiye", "Kordon", "Kemeraltı"]),
            TabooWord(goalWord: "Çanakkale", tabooWords: ["Şehir", "Boğaz", "Tarih", "Savaş", "Şehitlik"]),
            TabooWord(goalWord: "Ankara", tabooWords: ["Başkent", "Türkiye", "Şehir", "Meclis", "Atatürk"]),
            TabooWord(goalWord: "Kayseri", tabooWords: ["Şehir", "Pastırma", "Türkiye", "Erciyes", "Sanayi"]),
            TabooWord(goalWord: "Yozgat", tabooWords: ["Şehir", "İç Anadolu", "Türkiye", "Bozok", "İl"]),
            TabooWord(goalWord: "Descartes", tabooWords: ["Felsefe", "Matematik", "Filozof", "Düşünce", "Fransız"]),
            TabooWord(goalWord: "Kızgın", tabooWords: ["Öfkeli", "Sinirli", "Ateşli", "Hiddetli", "Küskün"]),
            TabooWord(goalWord: "Hafif", tabooWords: ["Ağırlık", "Yumuşak", "İnce", "Az", "Küçük"]),
            TabooWord(goalWord: "Buğu", tabooWords: ["Nem", "Buhar", "Cam", "Sis", "Görüş"]),
            TabooWord(goalWord: "Köftehor", tabooWords: ["Yemek", "Köfte", "Lakap", "Komik", "Küçük"]),
            TabooWord(goalWord: "Kayınca", tabooWords: ["Düşmek", "Kaymak", "Yol", "Kaza", "Buz"]),
            TabooWord(goalWord: "Baldız", tabooWords: ["Eş", "Kardeş", "Kadın", "Aile", "Kayın"]),
            TabooWord(goalWord: "Fatura", tabooWords: ["Ödeme", "Elektrik", "Su", "Doğalgaz", "Borç"]),
            TabooWord(goalWord: "Düğüm", tabooWords: ["İp", "Bağlamak", "Çözmek", "Karmaşık", "Sorun"]),
            TabooWord(goalWord: "Köpük", tabooWords: ["Sabun", "Banyo", "Şampuan", "Su", "Hafif"]),
            TabooWord(goalWord: "Parlak", tabooWords: ["Işık", "Aydınlık", "Göz kamaştırıcı", "Parıldayan", "Canlı"]),
            TabooWord(goalWord: "Yarış", tabooWords: ["Koşu", "Hız", "Mücadele", "Birincilik", "Rekabet"]),
            TabooWord(goalWord: "Söz verme", tabooWords: ["Yemin", "Taahhüt", "Güvence", "Söz", "Vaad"]),
            TabooWord(goalWord: "Duvar kağıdı", tabooWords: ["Dekorasyon", "Ev", "Duvar", "Kaplama", "Desen"]),
            TabooWord(goalWord: "Biber", tabooWords: ["Sebze", "Acı", "Yeşil", "Kırmızı", "Baharat"]),
            TabooWord(goalWord: "Politikacı", tabooWords: ["Siyaset", "Seçim", "Devlet", "Meclis", "Hükümet"]),
            TabooWord(goalWord: "Dizel", tabooWords: ["Yakıt", "Motor", "Araç", "Benzin", "Mazot"]),
            TabooWord(goalWord: "Zeytinyağı", tabooWords: ["Yemek", "Sağlık", "Akdeniz", "Salata", "Yağ"]),
            TabooWord(goalWord: "Cemre", tabooWords: ["Havaya", "Suya", "Toprağa", "Bahar", "Düşmek"]),
            TabooWord(goalWord: "Avrupa yakası", tabooWords: ["İstanbul", "Dizi", "Anadolu", "Kıta", "Yaka"]),
            TabooWord(goalWord: "Yarış", tabooWords: ["Koşu", "Hız", "Mücadele", "Birincilik", "Rekabet"]),
            TabooWord(goalWord: "Ödül", tabooWords: ["Kazanan", "Başarı", "Tören", "Hediye", "Madalya"]),
            TabooWord(goalWord: "Şampiyonluk", tabooWords: ["Birinci", "Kupa", "Başarı", "Lider", "Zafer"]),
            TabooWord(goalWord: "Motorsiklet", tabooWords: ["Araç", "İki tekerlek", "Hız", "Kask", "Motor"]),
            TabooWord(goalWord: "Dönme dolap", tabooWords: ["Lunapark", "Eğlence", "Büyük", "Tekerlek", "Manzara"]),
            TabooWord(goalWord: "Ganyan", tabooWords: ["Bahis", "At yarışı", "Kazanç", "Kupon", "Yarış"]),
            TabooWord(goalWord: "At yarışı", tabooWords: ["Ganyan", "Koşu", "At", "Bahis", "Hipodrom"]),
            TabooWord(goalWord: "Nabız", tabooWords: ["Kalp", "Atış", "Sağlık", "Damar", "Ölçüm"]),
            TabooWord(goalWord: "Parçalı bulutlu", tabooWords: ["Hava", "Bulut", "Güneş", "Meteoroloji", "Tahmin"]),
            TabooWord(goalWord: "Yağmur", tabooWords: ["Su", "Hava", "Islak", "Bulut", "Düşmek"]),
            TabooWord(goalWord: "Güneş", tabooWords: ["Işık", "Gökyüzü", "Isı", "Parlak", "Yıldız"]),
            TabooWord(goalWord: "Hava durumu", tabooWords: ["Tahmin", "Yağmur", "Güneş", "Meteoroloji", "Rüzgar"]),
            TabooWord(goalWord: "Transparan", tabooWords: ["Şeffaf", "Görünür", "Giysi", "Hafif", "Kıyafet"]),
            TabooWord(goalWord: "Maytap", tabooWords: ["Eğlence", "Ateş", "Kıvılcım", "Patlama", "Fişek"]),
            TabooWord(goalWord: "Fişek", tabooWords: ["Silah", "Patlama", "Mermi", "Maytap", "Ateş"]),
            TabooWord(goalWord: "Mantı", tabooWords: ["Yemek", "Hamur", "Türk", "Yoğurt", "İç"]),
            TabooWord(goalWord: "Şahit", tabooWords: ["Görgü", "Mahkeme", "Tanık", "Olay", "Anlatmak"]),
            TabooWord(goalWord: "Kabare", tabooWords: ["Eğlence", "Gösteri", "Müzikal", "Tiyatro", "Komedi"]),
            TabooWord(goalWord: "Gizem", tabooWords: ["Sır", "Çözülmemiş", "Esrarengiz", "Bilinmeyen", "Merak"]),
            TabooWord(goalWord: "Sır", tabooWords: ["Gizli", "Bilgi", "Açıklamak", "Gizem", "Korunmak"]),
            TabooWord(goalWord: "Doğaüstü", tabooWords: ["Gizemli", "Paranormal", "Olağanüstü", "Ruh", "Metafizik"]),
            TabooWord(goalWord: "Prematüre", tabooWords: ["Erken", "Bebek", "Doğum", "Olgunlaşmamış", "Sağlık"]),
            TabooWord(goalWord: "Mala", tabooWords: ["Alet", "İnşaat", "Duvar", "Sıva", "El"]),
            TabooWord(goalWord: "NASA", tabooWords: ["Uzay", "Amerika", "Ajans", "Roket", "Görev"]),
            TabooWord(goalWord: "Eli ağır", tabooWords: ["Yavaş", "Geç", "Zaman", "Beklemek", "Sabır"]),
            TabooWord(goalWord: "Çağan Irmak", tabooWords: ["Yönetmen", "Film", "Türk", "Sinema", "Senarist"]),
            TabooWord(goalWord: "Sinema", tabooWords: ["Film", "Perde", "Gösterim", "Tiyatro", "Yönetmen"]),
            TabooWord(goalWord: "Cinayet", tabooWords: ["Öldürmek", "Suç", "Polis", "Dedektif", "Katil"]),
            TabooWord(goalWord: "Dedektif", tabooWords: ["Araştırma", "Polis", "Suç", "Cinayet", "Gizem"]),
            TabooWord(goalWord: "Katil", tabooWords: ["Cinayet", "Suç", "Öldürmek", "Suçlu", "Dedektif"]),
            TabooWord(goalWord: "Feminen", tabooWords: ["Kadınsı", "Nazik", "Dişi", "Zarif", "Estetik"]),
            TabooWord(goalWord: "Kalıp", tabooWords: ["Şekil", "Model", "Form", "Döküm", "Matris"]),
            TabooWord(goalWord: "Patron", tabooWords: ["İşveren", "Yönetici", "Şef", "İş", "Firma"]),
            TabooWord(goalWord: "Sabun", tabooWords: ["Temizlik", "Köpük", "El", "Banyo", "Su"]),
            TabooWord(goalWord: "Panik", tabooWords: ["Korku", "Heyecan", "Endişe", "Acele", "Stres"]),
            TabooWord(goalWord: "Coğrafya", tabooWords: ["Yer", "Harita", "Bölge", "Dünya", "Kıta"]),
            TabooWord(goalWord: "Kaldıraç", tabooWords: ["Makine", "Kuvvet", "Hareket", "Yük", "Fizik"]),
            TabooWord(goalWord: "Dudu", tabooWords: ["Kadın", "İsim", "Aile", "Ad", "Şarkı"]),
            TabooWord(goalWord: "Cevher", tabooWords: ["Maden", "Altın", "Değerli", "Taş", "Zengin"]),
            TabooWord(goalWord: "Osmanlı", tabooWords: ["İmparatorluk", "Tarih", "Türkiye", "Padişah", "Saray"]),
            TabooWord(goalWord: "Menopoz", tabooWords: ["Kadın", "Yaş", "Dönem", "Hormonal", "Değişim"]),
            TabooWord(goalWord: "Hurda", tabooWords: ["Atık", "Metal", "Geri dönüşüm", "Eski", "Değersiz"]),
            TabooWord(goalWord: "Istakoz", tabooWords: ["Deniz", "Yemek", "Kabuklu", "Kırmızı", "Lüks"]),
            TabooWord(goalWord: "Boğa", tabooWords: ["Hayvan", "Sığır", "Boynuz", "Kırmızı", "Zodyak"]),
            TabooWord(goalWord: "Yengeç", tabooWords: ["Deniz", "Hayvan", "Kabuk", "Zodyak", "Yan"]),
            TabooWord(goalWord: "Kova", tabooWords: ["Su", "Zodyak", "Burç", "Kap", "Astroloji"]),
            TabooWord(goalWord: "Yay", tabooWords: ["Burç", "Zodyak", "Ok", "Astroloji", "Yay"]),
            TabooWord(goalWord: "RTÜK", tabooWords: ["Televizyon", "Radyo", "Yayın", "Kontrol", "Türkiye"]),
            TabooWord(goalWord: "Cetvel", tabooWords: ["Ölçmek", "Uzunluk", "Araç", "Çizgi", "Okul"]),
            TabooWord(goalWord: "Metre", tabooWords: ["Ölçü", "Uzunluk", "Mesafe", "Araç", "Metre"]),
            TabooWord(goalWord: "Öğretmen", tabooWords: ["Eğitim", "Okul", "Ders", "Sınıf", "Öğrenci"]),
            TabooWord(goalWord: "Doktor", tabooWords: ["Sağlık", "Hastane", "Tedavi", "Hasta", "Tıp"]),
            TabooWord(goalWord: "Savcı", tabooWords: ["Hukuk", "Dava", "Mahkeme", "Suç", "Adalet"]),
            TabooWord(goalWord: "Hakim", tabooWords: ["Mahkeme", "Adalet", "Yargı", "Dava", "Karar"]),
            TabooWord(goalWord: "Avukat", tabooWords: ["Hukuk", "Dava", "Mahkeme", "Savunma", "Müvekkil"]),
            TabooWord(goalWord: "Çemen", tabooWords: ["Baharat", "Yemek", "Sarımsak", "Bahar", "Acı"]),
            TabooWord(goalWord: "Çimen", tabooWords: ["Yeşil", "Bitki", "Çayır", "Bahçe", "Ot"]),
            TabooWord(goalWord: "Sarımsak", tabooWords: ["Baharat", "Yemek", "Koku", "Beyaz", "Sebze"]),
            TabooWord(goalWord: "Tokat", tabooWords: ["Vurmak", "Yüz", "Ceza", "El", "Şiddet"]),
            TabooWord(goalWord: "Dikiş makinası", tabooWords: ["Tekstil", "Giysi", "Dikmek", "Makine", "Terzi"]),
            TabooWord(goalWord: "Vergi", tabooWords: ["Ödeme", "Devlet", "Maliye", "Borc", "Yükümlülük"]),
            TabooWord(goalWord: "Devlet", tabooWords: ["Hükümet", "Ülke", "Yönetim", "Kamu", "Resmi"]),
            TabooWord(goalWord: "Maliye", tabooWords: ["Vergi", "Para", "Devlet", "Bütçe", "Ekonomi"]),
            TabooWord(goalWord: "Fatura", tabooWords: ["Ödeme", "Elektrik", "Su", "Doğalgaz", "Borç"]),
            TabooWord(goalWord: "Akbaba", tabooWords: ["Kuş", "Leş", "Yırtıcı", "Gökyüzü", "Kara"]),
            TabooWord(goalWord: "Haç", tabooWords: ["Din", "Hristiyan", "Sembol", "İnanç", "Çarmıh"]),
            TabooWord(goalWord: "Amortisör", tabooWords: ["Araç", "Süspansiyon", "Yol", "Konfor", "Şok emici"]),
            TabooWord(goalWord: "Haysiyet", tabooWords: ["Onur", "Şeref", "Gurur", "İtibar", "Saygı"]),
            TabooWord(goalWord: "Şeref", tabooWords: ["Onur", "Haysiyet", "İtibar", "Saygı", "Dürüstlük"]),
            TabooWord(goalWord: "Kasap", tabooWords: ["Et", "Bıçak", "Dükkan", "Hayvan", "Kıyma"]),
            TabooWord(goalWord: "İtfaiye", tabooWords: ["Yangın", "Su", "Araç", "Kurtarma", "Hortum"]),
            TabooWord(goalWord: "Federal", tabooWords: ["Devlet", "Birlik", "Hükümet", "ABD", "Yönetim"]),
            TabooWord(goalWord: "Depresyon", tabooWords: ["Ruh hali", "Hüzün", "Mutsuz", "Psikoloji", "Stres"]),
            TabooWord(goalWord: "Hudut", tabooWords: ["Sınır", "Ülke", "Çizgi", "Geçiş", "Kontrol"]),
            TabooWord(goalWord: "Kopmak", tabooWords: ["Ayrılmak", "Bağ", "Düşmek", "Kırılmak", "Parça"]),
            TabooWord(goalWord: "Tek taş", tabooWords: ["Yüzük", "Mücevher", "Evlilik", "Pırlanta", "Nişan"]),
            TabooWord(goalWord: "Evlenmek", tabooWords: ["Düğün", "Evlilik", "Nikah", "Gelir", "Aile"]),
            TabooWord(goalWord: "Alyans", tabooWords: ["Yüzük", "Evlilik", "Altın", "Nişan", "Parmak"]),
            TabooWord(goalWord: "Haciz", tabooWords: ["Borç", "Ödeme", "Devlet", "Mülk", "Mahkeme"]),
            TabooWord(goalWord: "Haber", tabooWords: ["Gazete", "Televizyon", "Bilgi", "Duyuru", "Medya"]),
            TabooWord(goalWord: "Sivrisinek", tabooWords: ["Böcek", "Isırmak", "Kan", "Vızıldamak", "Hastalık"]),
            TabooWord(goalWord: "Sıtma", tabooWords: ["Hastalık", "Ateş", "Parazit", "Sivrisinek", "Tropikal"]),
            TabooWord(goalWord: "Fiyonk", tabooWords: ["Kurdele", "Süs", "Bağlamak", "Dekorasyon", "Düğüm"]),
            TabooWord(goalWord: "Kemer", tabooWords: ["Pantolon", "Toka", "Sıkmak", "Bel", "Aksesuar"]),
            TabooWord(goalWord: "Kadınbudu", tabooWords: ["Köfte", "Yemek", "Et", "Pirinc", "Türk"]),
            TabooWord(goalWord: "Platform", tabooWords: ["Sahne", "Yüksek", "Zemin", "Yükselti", "Düzlem"]),
            TabooWord(goalWord: "İşlemci", tabooWords: ["Bilgisayar", "CPU", "Hız", "Donanım", "Teknoloji"]),
            TabooWord(goalWord: "RAM", tabooWords: ["Hafıza", "Bilgisayar", "Bellek", "Depolama", "Veri"]),
            TabooWord(goalWord: "SSD", tabooWords: ["Depolama", "Disk", "Bilgisayar", "Hızlı", "Veri"]),
            TabooWord(goalWord: "Kavis", tabooWords: ["Eğri", "Çizgi", "Dönmek", "Şekil", "Yol"]),
            TabooWord(goalWord: "Sevap", tabooWords: ["İyilik", "Dini", "Hayırlı", "İş", "Günah"]),
            TabooWord(goalWord: "Çeşme", tabooWords: ["Su", "Akmak", "İçmek", "Kaynak", "Sebil"]),
            TabooWord(goalWord: "Sedir", tabooWords: ["Mobilya", "Ağaç", "Yatak", "Oturmak", "Koltuk"]),
            TabooWord(goalWord: "Fiil", tabooWords: ["Dilbilgisi", "Eylem", "Kelime", "Yapmak", "Olmak"]),
            TabooWord(goalWord: "Tecrübe", tabooWords: ["Deneyim", "Yaşamak", "Bilgi", "Öğrenmek", "Geçmiş"]),
            TabooWord(goalWord: "Dedikodu", tabooWords: ["Söylenti", "Laf", "Konuşmak", "Arka", "Gizli"]),
            TabooWord(goalWord: "Personel", tabooWords: ["Çalışan", "İş", "Kadro", "İnsan", "Ofis"]),
            TabooWord(goalWord: "Şanzıman", tabooWords: ["Araç", "Vites", "Otomobil", "Motor", "Dişli"]),
            TabooWord(goalWord: "Vites", tabooWords: ["Şanzıman", "Araç", "Dişli", "Değiştirmek", "Hız"]),
            TabooWord(goalWord: "Muhasebe", tabooWords: ["Hesap", "Para", "İşletme", "Finans", "Defter"]),
            TabooWord(goalWord: "Daktilo", tabooWords: ["Yazmak", "Eski", "Mekanik", "Klavye", "Ofis"]),
            TabooWord(goalWord: "Kuşatma", tabooWords: ["Savaş", "Asker", "Şehir", "Kalmak", "Çevrelemek"]),
            TabooWord(goalWord: "Dalavere", tabooWords: ["Hile", "Oyun", "Kandırmak", "Entrika", "Yalan"]),
            TabooWord(goalWord: "Lunapark", tabooWords: ["Eğlence", "Dönme dolap", "Oyun", "Çocuk", "Park"]),
            TabooWord(goalWord: "Örgü", tabooWords: ["Elde", "İp", "Şiş", "Kazak", "Hobi"]),
            TabooWord(goalWord: "Galaksi", tabooWords: ["Uzay", "Yıldız", "Evren", "Samanyolu", "Gezegen"]),
            TabooWord(goalWord: "Tango", tabooWords: ["Dans", "Müzik", "Arjantin", "Partner", "Ritim"]),
            TabooWord(goalWord: "Kuş bakışı", tabooWords: ["Yüksek", "Üstten", "Manzara", "Harita", "Görüş"]),
            TabooWord(goalWord: "Piknik", tabooWords: ["Açık hava", "Yemek", "Doğa", "Aile", "Mangal"]),
            TabooWord(goalWord: "Tezgah", tabooWords: ["Satış", "Dükkan", "Market", "Masa", "Çalışmak"]),
            TabooWord(goalWord: "Hıçkırık", tabooWords: ["Nefes", "Ses", "Ani", "Durmak", "Göğüs"]),
            TabooWord(goalWord: "Rating", tabooWords: ["Televizyon", "Program", "İzlenme", "Sıralama", "Puan"]),
            TabooWord(goalWord: "Hamarat", tabooWords: ["Çalışkan", "Beceri", "İş", "Ev", "Yetenek"]),
            TabooWord(goalWord: "Hünerli", tabooWords: ["Yetenekli", "Maharetli", "Beceri", "Usta", "Başarı"]),
            TabooWord(goalWord: "Somon", tabooWords: ["Balık", "Deniz", "Pembe", "Lezzetli", "Besin"]),
            TabooWord(goalWord: "Füme", tabooWords: ["Duman", "Et", "Balık", "Tat", "Koku"]),
            TabooWord(goalWord: "Kar topu", tabooWords: ["Kış", "Oyun", "Beyaz", "Soğuk", "Karla"]),
            TabooWord(goalWord: "Nostalji", tabooWords: ["Geçmiş", "Hatıra", "Eski", "Anı", "Retro"]),
            TabooWord(goalWord: "Kesme şeker", tabooWords: ["Çay", "Tatlı", "Küp", "Beyaz", "Şeker"]),
            TabooWord(goalWord: "Olta", tabooWords: ["Balık", "Yakalamak", "Deniz", "Av", "Kamış"]),
            TabooWord(goalWord: "Rakı", tabooWords: ["Alkol", "Beyaz", "Anason", "İçki", "Türkiye"]),
            TabooWord(goalWord: "Bira", tabooWords: ["İçki", "Alkol", "Köpük", "Malt", "Şişe"]),
            TabooWord(goalWord: "Jeopolitik", tabooWords: ["Politika", "Coğrafya", "Ülke", "Güç", "Uluslararası"]),
            TabooWord(goalWord: "İntikam", tabooWords: ["Öç", "Kötülük", "Ceza", "Yenmek", "Düşman"]),
            TabooWord(goalWord: "Battal", tabooWords: ["Büyük", "Geniş", "Koca", "Boyut", "Giysi"]),
            TabooWord(goalWord: "Marjinal", tabooWords: ["Sıradışı", "Farklı", "Çizgi dışı", "Toplum", "Yeni"]),
            TabooWord(goalWord: "Susuzluk", tabooWords: ["Su", "İçmek", "Kuru", "Çöl", "Dehidrasyon"]),
            TabooWord(goalWord: "Dejavu", tabooWords: ["Anı", "Hissetmek", "Yaşamak", "Tanıdık", "Olay"]),
            TabooWord(goalWord: "Manita", tabooWords: ["Sevgili", "Argo", "Partner", "İlişki", "Aşk"]),
            TabooWord(goalWord: "Argo", tabooWords: ["Dil", "Küfür", "Konuşma", "Sokak", "Kelime"]),
            TabooWord(goalWord: "Arkadaş", tabooWords: ["Dost", "Kişi", "Yakın", "Samimi", "Tanıdık"]),
            TabooWord(goalWord: "Sevgili", tabooWords: ["Aşk", "İlişki", "Partner", "Manita", "Eş"]),
            TabooWord(goalWord: "İpucu", tabooWords: ["İşaret", "Bilgi", "Araştırma", "Çözmek", "Gizem"]),
            TabooWord(goalWord: "Tropikal", tabooWords: ["Ekvator", "Sıcak", "Orman", "Ada", "Meyve"]),
            TabooWord(goalWord: "Maki", tabooWords: ["Bitki", "Akdeniz", "Çalı", "Yeşil", "Kısa"]),
            TabooWord(goalWord: "Kabile", tabooWords: ["Halk", "Grup", "Gelenek", "Kültür", "Topluluk"]),
            TabooWord(goalWord: "Halk", tabooWords: ["Toplum", "İnsanlar", "Kültür", "Nüfus", "Ülke"]),
            TabooWord(goalWord: "Reis", tabooWords: ["Lider", "Başkan", "Kaptan", "Önder", "Yönetici"]),
            TabooWord(goalWord: "Priz", tabooWords: ["Elektrik", "Fiş", "Duvarda", "Takmak", "Güç"]),
            TabooWord(goalWord: "Tamirci", tabooWords: ["Onarmak", "Araç", "Usta", "Atölye", "Teknik"]),
            TabooWord(goalWord: "Tur", tabooWords: ["Gezi", "Seyahat", "Rehber", "Şehir", "Kültür"]),
            TabooWord(goalWord: "Fil dişi", tabooWords: ["Afrika", "Hayvan", "Diş", "Fildişi", "Beyaz"]),
            TabooWord(goalWord: "Afrika", tabooWords: ["Kıta", "Sıcak", "Ülke", "Vahşi", "Hayvan"]),
            TabooWord(goalWord: "Nedime", tabooWords: ["Düğün", "Gelinin arkadaşı", "Kadın", "Elbise", "Tören"]),
            TabooWord(goalWord: "İmtiyaz", tabooWords: ["Ayrıcalık", "Özel", "Hak", "Fırsat", "Yetki"]),
            TabooWord(goalWord: "Hokka", tabooWords: ["Mürekkep", "Kalem", "Yazı", "Eski", "Araç"]),
            TabooWord(goalWord: "Muhakeme", tabooWords: ["Düşünmek", "Yargı", "Analiz", "Karar", "Beyin"]),
            TabooWord(goalWord: "Taraf", tabooWords: ["Yan", "Seçim", "Yön", "Desteklemek", "Ekip"]),
            TabooWord(goalWord: "Tahammül", tabooWords: ["Dayanmak", "Sabır", "Katlanmak", "Hoşgörü", "Sinir"]),
            TabooWord(goalWord: "Kral", tabooWords: ["Monarşi", "Hükümdar", "Taç", "Ülke", "Yönetmek"]),
            TabooWord(goalWord: "Boynuz", tabooWords: ["Hayvan", "Baş", "Kıvrık", "Geyik", "Sert"]),
            TabooWord(goalWord: "Felsefe", tabooWords: ["Düşünce", "Bilim", "Anlayış", "Soru", "Akıl"]),
            TabooWord(goalWord: "Çakıl", tabooWords: ["Taş", "Küçük", "Kumsal", "Yol", "Yer"]),
            TabooWord(goalWord: "Yastık", tabooWords: ["Yatak", "Uyumak", "Kumaş", "Baş", "Rahat"]),
            TabooWord(goalWord: "Zihniyet", tabooWords: ["Düşünce", "Anlayış", "Bakış", "Kültür", "Tavır"]),
            TabooWord(goalWord: "Keder", tabooWords: ["Üzüntü", "Hüzün", "Acı", "Mutsuzluk", "Dert"]),
            TabooWord(goalWord: "Efkar", tabooWords: ["Düşünce", "Üzüntü", "Melankoli", "Hüzün", "Ağır"]),
            TabooWord(goalWord: "Günah", tabooWords: ["Suç", "Kötü", "Dini", "Yasak", "Cezalandırma"]),
            TabooWord(goalWord: "Paradoks", tabooWords: ["Çelişki", "Zıtlık", "Mantık", "Felsefe", "İkilem"]),
            TabooWord(goalWord: "Asistan", tabooWords: ["Yardımcı", "Destek", "Çalışan", "Ofis", "Sekreter"]),
            TabooWord(goalWord: "Kapan", tabooWords: ["Tuzak", "Kilit", "Yakalamak", "Fare", "Kapanmak"]),
            TabooWord(goalWord: "Halletmek", tabooWords: ["Çözmek", "Bitirmek", "Yapmak", "Görev", "Sorun"]),
            TabooWord(goalWord: "Panda", tabooWords: ["Hayvan", "Bambu", "Çin", "Ayı", "Sevimli"]),
            TabooWord(goalWord: "Dondurma", tabooWords: ["Tatlı", "Soğuk", "Külah", "Yaz", "Süt"]),
            TabooWord(goalWord: "Elektroliz", tabooWords: ["Kimya", "Ayrıştırmak", "Elektrik", "Sıvı", "İşlem"]),
            TabooWord(goalWord: "Tepki", tabooWords: ["Reaksiyon", "Cevap", "Davranış", "Etki", "Yanıt"]),
            TabooWord(goalWord: "Pazar", tabooWords: ["Gün", "Alışveriş", "Meyve", "Sebze", "Açık"]),
            TabooWord(goalWord: "Vapur", tabooWords: ["Deniz", "Taşıma", "Gemi", "İstanbul", "Buhar"]),
            TabooWord(goalWord: "Feribot", tabooWords: ["Deniz", "Araç", "Taşıma", "Seyahat", "Büyük"]),
            TabooWord(goalWord: "Bariyer", tabooWords: ["Engel", "Yol", "Geçit", "Araç", "Kapatmak"]),
            TabooWord(goalWord: "Modem", tabooWords: ["İnternet", "Bağlantı", "Cihaz", "Kablosuz", "Ağ"]),
            TabooWord(goalWord: "Wireless", tabooWords: ["Kablosuz", "İnternet", "Bağlantı", "WiFi", "Ağ"]),
            TabooWord(goalWord: "ADSL", tabooWords: ["İnternet", "Bağlantı", "Hız", "Telefon", "Çizgi"]),
            TabooWord(goalWord: "Jel", tabooWords: ["Kıvam", "Saç", "Şeffaf", "Sürülebilir", "Krem"]),
            TabooWord(goalWord: "Pıhtı", tabooWords: ["Kan", "Tıkanıklık", "Sağlık", "Topak", "Damar"]),
            TabooWord(goalWord: "Kontenjan", tabooWords: ["Kota", "Sınır", "Öğrenci", "Kabul", "Yer"]),
            TabooWord(goalWord: "Sigara", tabooWords: ["Tütün", "Duman", "Nikotin", "Bağımlılık", "İçmek"]),
            TabooWord(goalWord: "Duman", tabooWords: ["Yanma", "Tütün", "Sigara", "Hava", "Görmek"]),
            TabooWord(goalWord: "Ayyaş", tabooWords: ["Sarhoş", "İçki", "Alkolik", "Gece", "Meyhane"]),
            TabooWord(goalWord: "Toka", tabooWords: ["Saç", "Aksesuar", "Tutturmak", "Klips", "Güzel"]),
            TabooWord(goalWord: "Bijuteri", tabooWords: ["Takı", "Aksesuar", "Mağaza", "Kuyumcu", "Ucuz"]),
            TabooWord(goalWord: "Örnek", tabooWords: ["Model", "Numune", "Gösterim", "Temsil", "Tanıtım"]),
            TabooWord(goalWord: "Dejavu", tabooWords: ["Hissetmek", "Yaşamak", "Anı", "Tanıdık", "Olay"]),
            TabooWord(goalWord: "Caretta Caretta", tabooWords: ["Kaplumbağa", "Deniz", "Koruma", "Yumurta", "Nesli tükenmek"]),
            TabooWord(goalWord: "Kaplumbağa", tabooWords: ["Hayvan", "Yavaş", "Kabuğu", "Sürünmek", "Yeşil"]),
            TabooWord(goalWord: "Akdeniz", tabooWords: ["Deniz", "Bölge", "Türkiye", "Sıcak", "Turizm"]),
            TabooWord(goalWord: "Şadırvan", tabooWords: ["Su", "Fıskiye", "Çeşme", "Meydan", "Camii"]),
            TabooWord(goalWord: "Kelepçe", tabooWords: ["Polis", "Suçlu", "Tutmamak", "Bağlamak", "Metal"]),
            TabooWord(goalWord: "Sezaryen", tabooWords: ["Doğum", "Ameliyat", "Bebek", "Anne", "Cerrahi"]),
            TabooWord(goalWord: "Falso", tabooWords: ["Yanlış", "Hata", "Yanılmak", "Şaşırmak", "Yalan"]),
            TabooWord(goalWord: "Kaset", tabooWords: ["Müzik", "Kayıt", "Analog", "Çalmak", "Eski"]),
            TabooWord(goalWord: "Mesuliyet", tabooWords: ["Sorumluluk", "Görev", "Yükümlülük", "Cevap", "Üstlenmek"]),
            TabooWord(goalWord: "İç güveyi", tabooWords: ["Damat", "Evlenmek", "Kadın", "Aile", "Evlilik"]),
            TabooWord(goalWord: "Vitamin", tabooWords: ["Besin", "Sağlık", "Hap", "Güçlü", "Diyet"]),
            TabooWord(goalWord: "Osmanlı", tabooWords: ["İmparatorluk", "Tarih", "Padişah", "Devlet", "Türkiye"]),
            TabooWord(goalWord: "Padişah", tabooWords: ["Kral", "Osmanlı", "Taht", "Saray", "Yönetici"]),
            TabooWord(goalWord: "İmparator", tabooWords: ["Lider", "Monarşi", "Krallık", "Hükümdar", "Yönetmek"]),
            TabooWord(goalWord: "Kaleci", tabooWords: ["Futbol", "Gol", "Kurtarmak", "Spor", "File"]),
            TabooWord(goalWord: "File", tabooWords: ["Ağ", "Balık", "Kaleci", "Voleybol", "Tenis"]),
            TabooWord(goalWord: "Gol", tabooWords: ["Futbol", "Skor", "Kaleci", "Maç", "Top"]),
            TabooWord(goalWord: "Örümcek", tabooWords: ["Böcek", "Ağ", "Sekiz bacak", "Zehir", "Korkutucu"]),
            TabooWord(goalWord: "Faiz", tabooWords: ["Para", "Banka", "Kredi", "Borç", "Ödeme"]),
            TabooWord(goalWord: "Akustik", tabooWords: ["Ses", "Müzik", "Doğal", "Enstrüman", "Echo"]),
            TabooWord(goalWord: "Tahin", tabooWords: ["Pekmez", "Susam", "Tatlı", "Ezme", "Kahvaltı"]),
            TabooWord(goalWord: "Pekmez", tabooWords: ["Tahin", "Tatlı", "Şurup", "Kahvaltı", "Üzüm"]),
            TabooWord(goalWord: "Ferman", tabooWords: ["Emir", "Belge", "Osmanlı", "Padişah", "Yazılı"]),
            TabooWord(goalWord: "Göç", tabooWords: ["Taşınmak", "Yer değiştirmek", "Nüfus", "Hayvan", "Bölge"]),
            TabooWord(goalWord: "Kredi kartı", tabooWords: ["Banka", "Ödeme", "Plastik", "Borç", "Alışveriş"]),
            TabooWord(goalWord: "Taksit", tabooWords: ["Ödeme", "Bölmek", "Ay", "Kredi", "Alışveriş"]),
            TabooWord(goalWord: "Denizaltı", tabooWords: ["Gemi", "Su", "Askeri", "Derinlik", "Deniz"]),
            TabooWord(goalWord: "Tünek", tabooWords: ["Kuş", "Konmak", "Yüksek", "Dal", "Dinlenmek"]),
            TabooWord(goalWord: "Çıban", tabooWords: ["İltihap", "Cilt", "Şişlik", "Ağrı", "Rahatsızlık"]),
            TabooWord(goalWord: "Hindi", tabooWords: ["Kuş", "Et", "Yılbaşı", "Büyük", "Tüy"]),
            TabooWord(goalWord: "AVM", tabooWords: ["Alışveriş", "Merkez", "Mağaza", "Kapalı", "Gezi"]),
            TabooWord(goalWord: "Temelli", tabooWords: ["Kalıcı", "Sürekli", "Daimi", "Son", "Yerleşmek"]),
            TabooWord(goalWord: "Tavan", tabooWords: ["Çatı", "Yüksek", "Oda", "Bina", "Üst"]),
            TabooWord(goalWord: "Diplomat", tabooWords: ["Elçi", "Temsilci", "Devlet", "Politika", "Dışişleri"]),
            TabooWord(goalWord: "Cacık", tabooWords: ["Yoğurt", "Salatalık", "Meze", "Soğuk", "Yemek"]),
            TabooWord(goalWord: "Hıyar", tabooWords: ["Sebze", "Yeşil", "Salata", "Cacık", "Taze"]),
            TabooWord(goalWord: "Salatalık", tabooWords: ["Sebze", "Yeşil", "Cacık", "Hıyar", "Taze"]),
            TabooWord(goalWord: "Fanus", tabooWords: ["Kap", "Balık", "Cam", "Küçük", "Süs"]),
            TabooWord(goalWord: "Armağan", tabooWords: ["Hediye", "Vermek", "Ödül", "Değerli", "Eşya"]),
            TabooWord(goalWord: "Duvak", tabooWords: ["Gelin", "Nikah", "Baş", "Beyaz", "Dantel"]),
            TabooWord(goalWord: "Gurur", tabooWords: ["Onur", "Mutluluk", "Başarı", "Övünmek", "Kibir"]),
            TabooWord(goalWord: "Keratin", tabooWords: ["Protein", "Saç", "Tırnak", "Cilt", "Madde"]),
            TabooWord(goalWord: "Hiciv", tabooWords: ["Eleştiri", "Yergi", "Mizah", "Alay", "Yazı"]),
            TabooWord(goalWord: "Pisuvar", tabooWords: ["Tuvalet", "Erkek", "Kamu", "Lavabo", "Çiş"]),
            TabooWord(goalWord: "Fiyonk", tabooWords: ["Bağ", "Şerit", "Süs", "Kurdele", "Gelin"]),
            TabooWord(goalWord: "Ortodonti", tabooWords: ["Diş", "Tedavi", "Düzeltme", "Ağız", "Çene"]),
            TabooWord(goalWord: "Bamya", tabooWords: ["Sebze", "Yemek", "Yeşil", "Türk", "Tat"]),
            TabooWord(goalWord: "Vektör", tabooWords: ["Matematik", "Yön", "Uzunluk", "Birim", "Grafik"]),
            TabooWord(goalWord: "Köy", tabooWords: ["Küçük", "Yerleşim", "Kırsal", "Tarım", "Ev"]),
            TabooWord(goalWord: "Hulalop", tabooWords: ["Çember", "Dönmek", "Egzersiz", "Çocuk", "Oyuncak"]),
            TabooWord(goalWord: "Humus", tabooWords: ["Yemek", "Ortadoğu", "Nohut", "Ezme", "Meze"]),
            TabooWord(goalWord: "Penaltı", tabooWords: ["Futbol", "Gol", "Vuruş", "Ceza", "Maç"]),
            TabooWord(goalWord: "Payanda", tabooWords: ["Destek", "Kolon", "Mimari", "Güçlendirmek", "Yapı"]),
            TabooWord(goalWord: "Kadife", tabooWords: ["Kumaş", "Yumuşak", "Pürüzsüz", "Elbise", "Doku"]),
            TabooWord(goalWord: "Harakiri", tabooWords: ["Japon", "İntihar", "Samuray", "Onur", "Kılıç"]),
            TabooWord(goalWord: "Albay", tabooWords: ["Asker", "Rütbe", "Komutan", "Ordu", "Kıdemli"]),
            TabooWord(goalWord: "Asker", tabooWords: ["Ordu", "Savunma", "Komutan", "Rütbe", "Savaş"]),
            TabooWord(goalWord: "Galeta", tabooWords: ["Kurutulmuş", "Ekmek", "Çıtır", "Atıştırmalık", "Yemek"]),
            TabooWord(goalWord: "Komposto", tabooWords: ["Meyve", "Tatlı", "Sıvı", "Şeker", "Kuru"]),
            TabooWord(goalWord: "Mazgal", tabooWords: ["Kapağı", "Yol", "Yağmur", "Atık", "Kanal"]),
            TabooWord(goalWord: "Tenor", tabooWords: ["Şarkı", "Ses", "Müzik", "Opera", "Yüksek"]),
            TabooWord(goalWord: "Opera", tabooWords: ["Müzik", "Sahne", "Tiyatro", "Şarkı", "Klasik"]),
            TabooWord(goalWord: "Soprano", tabooWords: ["Şarkı", "Ses", "Yüksek", "Kadın", "Opera"]),
            TabooWord(goalWord: "Bariton", tabooWords: ["Ses", "Şarkı", "Erkek", "Orta", "Müzik"]),
            TabooWord(goalWord: "Mancınık", tabooWords: ["Fırlatmak", "Silah", "Ortaçağ", "Savaş", "Taş"]),
            TabooWord(goalWord: "Mecaz", tabooWords: ["Söz", "Anlam", "İfade", "Değişik", "Kavram"]),
            TabooWord(goalWord: "Köle", tabooWords: ["Esir", "Çalıştırmak", "Sahip", "Özgürlük", "Tarih"]),
            TabooWord(goalWord: "Korniş", tabooWords: ["Perde", "Askı", "Pencere", "Ev", "Süs"]),
            TabooWord(goalWord: "Düşeş", tabooWords: ["Zar", "Oyun", "Çift", "Altı", "Atmak"]),
            TabooWord(goalWord: "Bonkör", tabooWords: ["Cömert", "Vermek", "Yardım", "Eli açık", "Fedakar"]),
            TabooWord(goalWord: "Salyangoz", tabooWords: ["Kabuk", "Yavaş", "Hayvan", "Böcek", "Çiftleşme"]),
            TabooWord(goalWord: "Jile", tabooWords: ["Kesmek", "Bıçak", "Tıraş", "Alet", "Ustura"]),
            TabooWord(goalWord: "Güneş gözlüğü", tabooWords: ["Göz", "Yaz", "Koruma", "Aksesuar", "Gözlük"]),
            TabooWord(goalWord: "Pastil", tabooWords: ["Boğaz", "İlaç", "Emmek", "Hap", "Yumuşatmak"]),
            TabooWord(goalWord: "Gırtlak", tabooWords: ["Boğaz", "Ses", "Yemek", "Tüp", "Organ"]),
            TabooWord(goalWord: "Saksı", tabooWords: ["Çiçek", "Toprak", "Kap", "Balkon", "Bitki"])
            
            
        ]
            
            
            
        
            

    private var availableTabooWords: [TabooWord]
    
    init() {
        self.availableTabooWords = tabooWords.shuffled()
        print("Tüm kelimeler karıştırıldı: \(availableTabooWords.map { $0.goalWord })")
    }
    
    func getRandomTabooWord() -> TabooWord? {
        guard !availableTabooWords.isEmpty else {
            return nil
        }
        
        let selectedWord = availableTabooWords.removeFirst()
        print("Seçilen kelime: \(selectedWord.goalWord)")
        // print("Kalan kelimeler: \(availableTabooWords.map { $0.goalWord })")
        return selectedWord
    }
    
    func selectRandomTabooWordAndIncreaseScore() -> TabooWord? {
        if let randomTabooWord = getRandomTabooWord() {
            increaseScore()
            return randomTabooWord
        } else {
            
            return nil
        }
    }
    
    func increaseScore() {
        score += 1
    }
    
    func resetGame() {
        availableTabooWords = tabooWords.shuffled()
        score = 0
        passAttempts = 3
        //print("Oyun sıfırlandı. Yeni kelimeler: \(availableTabooWords.map { $0.goalWord })")
    }
}


